<a href="https://colab.research.google.com/github/henriquefernandes95/RAG_GRAPH_ALLIGN/blob/main/SBERT_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install sentence_transformers

Requirement already satisfied: sentence_transformers in /usr/local/lib/python3.12/dist-packages (5.2.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (4.57.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (2.9.0+cu126)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (1.16.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (0.36.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (3.20.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (2.32.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.5.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence_transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence_transformers) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence_transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (2026.1.4)

# Short Test

In [ ]:
"""
This is a simple application for sentence embeddings: semantic search

We have a corpus with various sentences. Then, for a given query sentence,
we want to find the most similar sentence in this corpus.

This script outputs for various queries the top 5 most similar sentences in the corpus.
"""

import torch

from sentence_transformers import SentenceTransformer

embedder = SentenceTransformer("google/embeddinggemma-300m")

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

modules.json:   0%|          | 0.00/573 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/997 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/18.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/58.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.49k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.21G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.69M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/312 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/134 [00:00<?, ?B/s]

2_Dense/model.safetensors:   0%|          | 0.00/9.44M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/134 [00:00<?, ?B/s]

3_Dense/model.safetensors:   0%|          | 0.00/9.44M [00:00<?, ?B/s]

In [ ]:
corpus = []

# Conjunto de teste

In [ ]:
corpus.append('''<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	xmlns:rdf4j="http://rdf4j.org/schema/rdf4j#"
	xmlns:sesame="http://www.openrdf.org/schema/sesame#"
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
	xmlns:fn="http://www.w3.org/2005/xpath-functions#">

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4362">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:label>disease</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:4</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4362">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050686"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_0050686">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:label>organ system cancer</rdfs:label>
	<created_by xmlns="http://www.geneontology.org/formats/oboInOwl#">snadendla</created_by>
	<creation_date xmlns="http://www.geneontology.org/formats/oboInOwl#">2011-06-13T03:28:33Z</creation_date>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0050686</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4362">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_162">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:comment>Updating out dated UMLS CUI.</rdfs:comment>
	<rdfs:label>cancer</rdfs:label>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant neoplasm</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant tumor </hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">primary cancer</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:162</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_AGR_slim"/>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4362">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_14566">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:label>disease of cellular proliferation</rdfs:label>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0000818</hasAlternativeId>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">neoplasm</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">cell process disease</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:14566</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4362">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_120"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_120">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050686"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_193"/>
	<rdfs:label>female reproductive organ cancer</rdfs:label>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1244</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1281</hasAlternativeId>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">female reproductive cancer</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant neoplasm of female genital organ</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:120</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4362">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_193"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_193">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050686"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:label>reproductive organ cancer</rdfs:label>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1900</hasAlternativeId>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant reproductive system neoplasm</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<hasRelatedSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">cancer of reproductive system</hasRelatedSynonym>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:193</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_MGI_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4362">
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_cancer_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/doid#DO_cancer_slim">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#AnnotationProperty"/>
	<rdfs:subPropertyOf rdf:resource="http://www.geneontology.org/formats/oboInOwl#SubsetProperty"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4362">
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#TopNodes_DOcancerslim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/doid#TopNodes_DOcancerslim">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#AnnotationProperty"/>
	<rdfs:subPropertyOf rdf:resource="http://www.geneontology.org/formats/oboInOwl#SubsetProperty"/>
</rdf:Description>

</rdf:RDF>''')

In [ ]:
corpus.append('''<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	xmlns:rdf4j="http://rdf4j.org/schema/rdf4j#"
	xmlns:sesame="http://www.openrdf.org/schema/sesame#"
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
	xmlns:fn="http://www.w3.org/2005/xpath-functions#">

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:label>disease</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:4</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050686"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_0050686">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:label>organ system cancer</rdfs:label>
	<created_by xmlns="http://www.geneontology.org/formats/oboInOwl#">snadendla</created_by>
	<creation_date xmlns="http://www.geneontology.org/formats/oboInOwl#">2011-06-13T03:28:33Z</creation_date>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0050686</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_1612"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_1612">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050686"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0060118"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_3463"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_5093"/>
	<rdfs:comment>Xref MGI.
OMIM mapping confirmed by DO. [SN].</rdfs:comment>
	<rdfs:label>breast cancer</rdfs:label>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1648</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:4241</hasAlternativeId>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant neoplasm of breast</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">mammary cancer</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">primary breast cancer</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<hasRelatedSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">mammary neoplasm</hasRelatedSynonym>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1612</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_cancer_slim"/>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#TopNodes_DOcancerslim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_162">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:comment>Updating out dated UMLS CUI.</rdfs:comment>
	<rdfs:label>cancer</rdfs:label>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant neoplasm</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant tumor </hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">primary cancer</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:162</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_AGR_slim"/>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_14566">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:label>disease of cellular proliferation</rdfs:label>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0000818</hasAlternativeId>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">neoplasm</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">cell process disease</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:14566</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0060118"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_0060118">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
	<rdfs:label>thoracic disease</rdfs:label>
	<created_by xmlns="http://www.geneontology.org/formats/oboInOwl#">lschriml</created_by>
	<creation_date xmlns="http://www.geneontology.org/formats/oboInOwl#">2011-07-25T02:23:47Z</creation_date>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0060118</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_AGR_slim"/>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_MGI_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_7">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:label>disease of anatomical entity</rdfs:label>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:2</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:5</hasAlternativeId>
	<hasAlter''')

In [ ]:
corpus.append('''<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	xmlns:rdf4j="http://rdf4j.org/schema/rdf4j#"
	xmlns:sesame="http://www.openrdf.org/schema/sesame#"
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
	xmlns:fn="http://www.w3.org/2005/xpath-functions#">

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_438">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:label>disease</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:4</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_438">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_417"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_417">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0060056"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_2914"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
	<rdfs:comment>Xref MGI.</rdfs:comment>
	<rdfs:label>hypersensitivity reaction type II disease</rdfs:label>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">autoimmune disease</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:417</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_438">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0060056"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_0060056">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_2914"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
	<rdfs:label>hypersensitivity reaction disease</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0060056</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_MGI_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_438">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_2914"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_2914">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
	<rdfs:label>immune system disease</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:2914</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_AGR_slim"/>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_MGI_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_438">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_7">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:label>disease of anatomical entity</rdfs:label>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:2</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:5</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:71</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:72</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:8</hasAlternativeId>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:7</id>
</rdf:Description>

</rdf:RDF>''')

In [ ]:
corpus.append('''<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	xmlns:rdf4j="http://rdf4j.org/schema/rdf4j#"
	xmlns:sesame="http://www.openrdf.org/schema/sesame#"
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
	xmlns:fn="http://www.w3.org/2005/xpath-functions#">

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4360">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:label>disease</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:4</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4360">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_162">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:comment>Updating out dated UMLS CUI.</rdfs:comment>
	<rdfs:label>cancer</rdfs:label>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant neoplasm</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant tumor </hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">primary cancer</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:162</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_AGR_slim"/>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4360">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050687"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_0050687">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:label>cell type cancer</rdfs:label>
	<created_by xmlns="http://www.geneontology.org/formats/oboInOwl#">snadendla</created_by>
	<creation_date xmlns="http://www.geneontology.org/formats/oboInOwl#">2011-06-13T03:28:50Z</creation_date>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0050687</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_MGI_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4360">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_1909"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_1909">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050687"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:label>melanoma</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1909</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#TopNodes_DOcancerslim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4360">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_14566">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:label>disease of cellular proliferation</rdfs:label>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0000818</hasAlternativeId>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">neoplasm</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">cell process disease</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:14566</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>
</rdf:Description>

</rdf:RDF>''')

In [ ]:
corpus.append('''<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	xmlns:rdf4j="http://rdf4j.org/schema/rdf4j#"
	xmlns:sesame="http://www.openrdf.org/schema/sesame#"
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
	xmlns:fn="http://www.w3.org/2005/xpath-functions#">

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4359">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:label>disease</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:4</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4359">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_162">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:comment>Updating out dated UMLS CUI.</rdfs:comment>
	<rdfs:label>cancer</rdfs:label>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant neoplasm</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant tumor </hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">primary cancer</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:162</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_AGR_slim"/>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4359">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050687"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_0050687">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:label>cell type cancer</rdfs:label>
	<created_by xmlns="http://www.geneontology.org/formats/oboInOwl#">snadendla</created_by>
	<creation_date xmlns="http://www.geneontology.org/formats/oboInOwl#">2011-06-13T03:28:50Z</creation_date>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0050687</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_MGI_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4359">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_1909"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_1909">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050687"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:label>melanoma</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1909</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#TopNodes_DOcancerslim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4359">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_14566">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:label>disease of cellular proliferation</rdfs:label>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0000818</hasAlternativeId>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">neoplasm</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">cell process disease</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:14566</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>
</rdf:Description>

</rdf:RDF>''')

In [ ]:
corpus.append('''<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	xmlns:rdf4j="http://rdf4j.org/schema/rdf4j#"
	xmlns:sesame="http://www.openrdf.org/schema/sesame#"
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
	xmlns:fn="http://www.w3.org/2005/xpath-functions#">

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4353">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:label>disease</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:4</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4353">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050155"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_0050155">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_863"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
	<rdfs:label>sensory system disease</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0050155</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4353">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_863"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_863">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
	<rdfs:label>nervous system disease</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:863</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_AGR_slim"/>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_MGI_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4353">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_5614"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_5614">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050155"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_863"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_1492"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
	<rdfs:label>eye disease</rdfs:label>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:2933</hasAlternativeId>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:5614</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4353">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_1492"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_1492">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050155"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_863"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
	<rdfs:label>eye and adnexa disease</rdfs:label>
	<use_in_alignment xmlns="http://oaei.ontologymatching.org/bio-ml/ann/" rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">false</use_in_alignment>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1492</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4353">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_7">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:label>disease of anatomical entity</rdfs:label>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:2</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:5</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:71</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:72</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:8</hasAlternativeId>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:7</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4353">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_240"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_240">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050155"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_863"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_5614"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_1492"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_3480"/>
	<rdfs:label>iris disease</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:240</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4353">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_3480"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_3480">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050155"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_863"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_5614"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_1492"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
	<rdfs:label>uveal disease</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:3480</id>
</rdf:Description>

</rdf:RDF>''')

In [ ]:
corpus

['<?xml version="1.0" encoding="UTF-8"?>\n<rdf:RDF\n\txmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"\n\txmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"\n\txmlns:rdf4j="http://rdf4j.org/schema/rdf4j#"\n\txmlns:sesame="http://www.openrdf.org/schema/sesame#"\n\txmlns:owl="http://www.w3.org/2002/07/owl#"\n\txmlns:xsd="http://www.w3.org/2001/XMLSchema#"\n\txmlns:fn="http://www.w3.org/2005/xpath-functions#">\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4362">\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4">\n\t<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>\n\t<rdfs:label>disease</rdfs:label>\n\t<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>\n\t<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:4</id>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4362">\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050686"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_0050686">\n\t<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>\n\t<rdfs:label>organ system cancer</rdfs:label>\n\t<created_by xmlns="http://www.geneontology.org/formats/oboInOwl#">snadendla</created_by>\n\t<creation_date xmlns="http://www.geneontology.org/formats/oboInOwl#">2011-06-13T03:28:33Z</creation_date>\n\t<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>\n\t<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0050686</id>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4362">\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_162">\n\t<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>\n\t<rdfs:comment>Updating out dated UMLS CUI.</rdfs:comment>\n\t<rdfs:label>cancer</rdfs:label>\n\t<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant neoplasm</hasExactSynonym>\n\t<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant tumor </hasExactSynonym>\n\t<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">primary cancer</hasExactSynonym>\n\t<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>\n\t<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:162</id>\n\t<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_AGR_slim"/>\n\t<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4362">\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_14566">\n\t<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>\n\t<rdfs:label>disease of cellular proliferation</rdfs:label>\n\t<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0000818</hasAlternativeId>\n\t<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">neoplasm</hasExactSynonym>\n\t<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">cell process disease</hasExactSynonym>\n\t<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>\n\t<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:14566</id>\n\t<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4362">\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_120"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_120">\n\t<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050686"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_193"/>\n\t<rdfs:label>female reproductive organ cancer</rdfs:label>\n\t<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1244</hasAlternativeId>\n\t<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1281</hasAlternativeId>\n\t<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">female reproductive cancer</hasExactSynonym>\n\t<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant neoplasm of female genital organ</hasExactSynonym>\n\t<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>\n\t<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:120</id>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4362">\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_193"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_193">\n\t<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050686"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>\n\t<rdfs:label>reproductive organ cancer</rdfs:label>\n\t<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1900</hasAlternativeId>\n\t<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant reproductive system neoplasm</hasExactSynonym>\n\t<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>\n\t<hasRelatedSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">cancer of reproductive system</hasRelatedSynonym>\n\t<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:193</id>\n\t<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_MGI_slim"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4362">\n\t<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_cancer_slim"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/doid#DO_cancer_slim">\n\t<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#AnnotationProperty"/>\n\t<rdfs:subPropertyOf rdf:resource="http://www.geneontology.org/formats/oboInOwl#SubsetProperty"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4362">\n\t<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#TopNodes_DOcancerslim"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/doid#TopNodes_DOcancerslim">\n\t<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#AnnotationProperty"/>\n\t<rdfs:subPropertyOf rdf:resource="http://www.geneontology.org/formats/oboInOwl#SubsetProperty"/>\n</rdf:Description>\n\n</rdf:RDF>',
 '<?xml version="1.0" encoding="UTF-8"?>\n<rdf:RDF\n\txmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"\n\txmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"\n\txmlns:rdf4j="http://rdf4j.org/schema/rdf4j#"\n\txmlns:sesame="http://www.openrdf.org/schema/sesame#"\n\txmlns:owl="http://www.w3.org/2002/07/owl#"\n\txmlns:xsd="http://www.w3.org/2001/XMLSchema#"\n\txmlns:fn="http://www.w3.org/2005/xpath-functions#">\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4">\n\t<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>\n\t<rdfs:label>disease</rdfs:label>\n\t<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>\n\t<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:4</id>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050686"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_0050686">\n\t<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>\n\t<rdfs:label>organ system cancer</rdfs:label>\n\t<created_by xmlns="http://www.geneontology.org/formats/oboInOwl#">snadendla</created_by>\n\t<creation_date xmlns="http://www.geneontology.org/formats/oboInOwl#">2011-06-13T03:28:33Z</creation_date>\n\t<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>\n\t<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0050686</id>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_1612"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_1612">\n\t<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050686"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0060118"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_3463"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_5093"/>\n\t<rdfs:comment>Xref MGI.\nOMIM mapping confirmed by DO. [SN].</rdfs:comment>\n\t<rdfs:label>breast cancer</rdfs:label>\n\t<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1648</hasAlternativeId>\n\t<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:4241</hasAlternativeId>\n\t<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant neoplasm of breast</hasExactSynonym>\n\t<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">mammary cancer</hasExactSynonym>\n\t<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">primary breast cancer</hasExactSynonym>\n\t<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>\n\t<hasRelatedSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">mammary neoplasm</hasRelatedSynonym>\n\t<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1612</id>\n\t<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_cancer_slim"/>\n\t<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#TopNodes_DOcancerslim"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_162">\n\t<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>\n\t<rdfs:comment>Updating out dated UMLS CUI.</rdfs:comment>\n\t<rdfs:label>cancer</rdfs:label>\n\t<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant neoplasm</hasExactSynonym>\n\t<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant tumor </hasExactSynonym>\n\t<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">primary cancer</hasExactSynonym>\n\t<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>\n\t<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:162</id>\n\t<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_AGR_slim"/>\n\t<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_14566">\n\t<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>\n\t<rdfs:label>disease of cellular proliferation</rdfs:label>\n\t<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0000818</hasAlternativeId>\n\t<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">neoplasm</hasExactSynonym>\n\t<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">cell process disease</hasExactSynonym>\n\t<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>\n\t<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:14566</id>\n\t<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0060118"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_0060118">\n\t<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>\n\t<rdfs:label>thoracic disease</rdfs:label>\n\t<created_by xmlns="http://www.geneontology.org/formats/oboInOwl#">lschriml</created_by>\n\t<creation_date xmlns="http://www.geneontology.org/formats/oboInOwl#">2011-07-25T02:23:47Z</creation_date>\n\t<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>\n\t<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0060118</id>\n\t<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_AGR_slim"/>\n\t<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_MGI_slim"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>\n</rdf:Description>\n\n<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_7">\n\t<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>\n\t<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>\n\t<rdfs:label>disease of anatomical entity</rdfs:label>\n\t<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1</hasAlternativeId>\n\t<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:2</hasAlternativeId>\n\t<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:5</hasAlternativeId>\n\t<hasAlter',

In [ ]:
# Use "convert_to_tensor=True" to keep the tensors on GPU (if available)
corpus_embeddings = embedder.encode_document(corpus, convert_to_tensor=True)

In [ ]:
!pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.13.1-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.6 kB)
Requirement already satisfied: numpy<3.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (25.0)
Downloading faiss_cpu-1.13.1-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (23.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 69.6 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.13.1

In [ ]:
import faiss
import numpy as np

index = faiss.IndexFlatL2(corpus_embeddings.shape[1])
index.add(corpus_embeddings)

In [ ]:
import faiss
import numpy as np
import torch  # only if corpus_embeddings is a torch.Tensor

# If corpus_embeddings is a PyTorch tensor on GPU:
embeddings_np = corpus_embeddings.detach().cpu().numpy().astype('float32')

# Create index and add vectors
d = embeddings_np.shape[1]
index = faiss.IndexFlatL2(d)
index.add(embeddings_np)

In [ ]:
index.ntotal

6

**Save Embeddings to File**

In [ ]:
import torch
torch.save(corpus_embeddings.detach().cpu(), "embeddings.pt")

**Load Embeddings**

In [ ]:
import torch

# load file (could be a tensor or a dict)
data = torch.load("embeddings.pt")

# get tensor
if isinstance(data, dict) and "embeddings" in data:
    emb_t = data["embeddings"]
else:
    emb_t = data

# ensure float32 and on the device you will use for similarity
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
corpus_embeddings = emb_t.detach().to(device).float()   # shape [N, D]

# Using FAISS

In [ ]:
import faiss
import numpy as np
import torch
from sentence_transformers import util

# load faiss index
index = faiss.read_index("index.faiss")

# encode query as tensor, convert to numpy float32
q_t = embedder.encode_query("your query", convert_to_tensor=True)
q_np = q_t.detach().cpu().numpy().astype("float32")

# if index was built with normalized vectors for cosine, normalize query too
faiss.normalize_L2(q_np)

# search
k = 5
D, I = index.search(q_np, k)   # I are row indices or IDs depending on index
# map indices back to documents using your saved metadata list

RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at /project/third-party/faiss/faiss/impl/io.cpp:69: Error: 'f' failed: could not open index.faiss for reading: No such file or directory

In [ ]:
# Query sentences:
queries = []

# Input Test

In [ ]:
queries.append('''<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	xmlns:rdf4j="http://rdf4j.org/schema/rdf4j#"
	xmlns:sesame="http://www.openrdf.org/schema/sesame#"
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
	xmlns:fn="http://www.w3.org/2005/xpath-functions#">

<rdf:Description rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C9311">
	<rdfs:subClassOf rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C9311"/>
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:nodeID="node122781"/>
	<owl:equivalentClass rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C9311"/>
	<owl:equivalentClass rdf:nodeID="node122781"/>
	<rdfs:label>Malignant Cervical Neoplasm</rdfs:label>
	<NHC0 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">C9311</NHC0>
	<P106 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Neoplastic Process</P106>
	<P108 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Cervical Neoplasm</P108>
	<P207 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">C0007847</P207>
	<P363 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant</P363>
	<P366 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant_Cervical_Neoplasm</P366>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Cervical Neoplasm</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Cervical Tumor</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Cervix Neoplasm</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Cervix Tumor</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Cervix Uteri Neoplasm</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Cervix Uteri Tumor</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Neoplasm of Cervix</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Neoplasm of Cervix Uteri</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Neoplasm of Uterine Cervix</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Neoplasm of the Cervix</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Neoplasm of the Cervix Uteri</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Neoplasm of the Uterine Cervix</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Tumor of Cervix</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Tumor of Cervix Uteri</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Tumor of Uterine Cervix</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Tumor of the Cervix</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Tumor of the Cervix Uteri</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Tumor of the Uterine Cervix</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Uterine Cervix Neoplasm</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Uterine Cervix Tumor</P90>
	<P97 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">A primary or metastatic malignant neoplasm involving the cervix.</P97>
</rdf:Description>

<rdf:Description rdf:nodeID="node122781">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C9311"/>
	<rdfs:subClassOf rdf:nodeID="node122781"/>
	<owl:equivalentClass rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C9311"/>
	<owl:equivalentClass rdf:nodeID="node122781"/>
	<owl:intersectionOf rdf:nodeID="node122782"/>
</rdf:Description>

</rdf:RDF>''')

# Similarity

In [ ]:

from sentence_transformers import util

# Find the closest 5 sentences of the corpus for each query sentence based on cosine similarity
top_k = min(5, len(corpus))
for query in queries:
    query_embedding = embedder.encode_query(query, convert_to_tensor=True)

    # We use cosine-similarity and torch.topk to find the highest 5 scores
    similarity_scores = embedder.similarity(query_embedding, corpus_embeddings)[0]
    scores, indices = torch.topk(similarity_scores, k=top_k)

    print("\nQuery:", query)
    print("Top 5 most similar sentences in corpus:")

    for score, idx in zip(scores, indices):
        print(f"(Score: {score:.4f})", corpus[idx])

    '''
    # Alternatively, we can also use util.semantic_search to perform cosine similarty + topk
    hits = util.semantic_search(query_embedding, corpus_embeddings, top_k=5)
    hits = hits[0]      #Get the hits for the first query
    for hit in hits:
        print(corpus[hit['corpus_id']], "(Score: {:.4f})".format(hit['score']))
    '''

Query: <?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	xmlns:rdf4j="http://rdf4j.org/schema/rdf4j#"
	xmlns:sesame="http://www.openrdf.org/schema/sesame#"
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
	xmlns:fn="http://www.w3.org/2005/xpath-functions#">

<rdf:Description rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C9311">
	<rdfs:subClassOf rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C9311"/>
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:nodeID="node122781"/>
	<owl:equivalentClass rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C9311"/>
	<owl:equivalentClass rdf:nodeID="node122781"/>
	<rdfs:label>Malignant Cervical Neoplasm</rdfs:label>
	<NHC0 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">C9311</NHC0>
	<P106 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Neoplastic Process</P106>
	<P108 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Cervical Neoplasm</P108>
	<P207 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">C0007847</P207>
	<P363 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant</P363>
	<P366 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant_Cervical_Neoplasm</P366>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Cervical Neoplasm</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Cervical Tumor</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Cervix Neoplasm</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Cervix Tumor</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Cervix Uteri Neoplasm</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Cervix Uteri Tumor</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Neoplasm of Cervix</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Neoplasm of Cervix Uteri</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Neoplasm of Uterine Cervix</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Neoplasm of the Cervix</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Neoplasm of the Cervix Uteri</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Neoplasm of the Uterine Cervix</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Tumor of Cervix</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Tumor of Cervix Uteri</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Tumor of Uterine Cervix</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Tumor of the Cervix</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Tumor of the Cervix Uteri</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Tumor of the Uterine Cervix</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Uterine Cervix Neoplasm</P90>
	<P90 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">Malignant Uterine Cervix Tumor</P90>
	<P97 xmlns="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#">A primary or metastatic malignant neoplasm involving the cervix.</P97>
</rdf:Description>

<rdf:Description rdf:nodeID="node122781">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C9311"/>
	<rdfs:subClassOf rdf:nodeID="node122781"/>
	<owl:equivalentClass rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C9311"/>
	<owl:equivalentClass rdf:nodeID="node122781"/>
	<owl:intersectionOf rdf:nodeID="node122782"/>
</rdf:Description>

</rdf:RDF>
Top 5 most similar sentences in corpus:
(Score: 0.7874) <?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	xmlns:rdf4j="http://rdf4j.org/schema/rdf4j#"
	xmlns:sesame="http://www.openrdf.org/schema/sesame#"
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
	xmlns:fn="http://www.w3.org/2005/xpath-functions#">

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:label>disease</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:4</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050686"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_0050686">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:label>organ system cancer</rdfs:label>
	<created_by xmlns="http://www.geneontology.org/formats/oboInOwl#">snadendla</created_by>
	<creation_date xmlns="http://www.geneontology.org/formats/oboInOwl#">2011-06-13T03:28:33Z</creation_date>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0050686</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_1612"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_1612">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050686"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0060118"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_3463"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_5093"/>
	<rdfs:comment>Xref MGI.
OMIM mapping confirmed by DO. [SN].</rdfs:comment>
	<rdfs:label>breast cancer</rdfs:label>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1648</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:4241</hasAlternativeId>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant neoplasm of breast</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">mammary cancer</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">primary breast cancer</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<hasRelatedSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">mammary neoplasm</hasRelatedSynonym>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1612</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_cancer_slim"/>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#TopNodes_DOcancerslim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_162">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:comment>Updating out dated UMLS CUI.</rdfs:comment>
	<rdfs:label>cancer</rdfs:label>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant neoplasm</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant tumor </hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">primary cancer</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:162</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_AGR_slim"/>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_14566">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:label>disease of cellular proliferation</rdfs:label>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0000818</hasAlternativeId>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">neoplasm</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">cell process disease</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:14566</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0060118"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_0060118">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
	<rdfs:label>thoracic disease</rdfs:label>
	<created_by xmlns="http://www.geneontology.org/formats/oboInOwl#">lschriml</created_by>
	<creation_date xmlns="http://www.geneontology.org/formats/oboInOwl#">2011-07-25T02:23:47Z</creation_date>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0060118</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_AGR_slim"/>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_MGI_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4364">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_7">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:label>disease of anatomical entity</rdfs:label>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:2</hasAlternativeId>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:5</hasAlternativeId>
	<hasAlter
(Score: 0.7870) <?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	xmlns:rdf4j="http://rdf4j.org/schema/rdf4j#"
	xmlns:sesame="http://www.openrdf.org/schema/sesame#"
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
	xmlns:fn="http://www.w3.org/2005/xpath-functions#">

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4359">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:label>disease</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:4</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4359">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_162">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:comment>Updating out dated UMLS CUI.</rdfs:comment>
	<rdfs:label>cancer</rdfs:label>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant neoplasm</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant tumor </hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">primary cancer</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:162</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_AGR_slim"/>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4359">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050687"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_0050687">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:label>cell type cancer</rdfs:label>
	<created_by xmlns="http://www.geneontology.org/formats/oboInOwl#">snadendla</created_by>
	<creation_date xmlns="http://www.geneontology.org/formats/oboInOwl#">2011-06-13T03:28:50Z</creation_date>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0050687</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_MGI_slim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4359">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_1909"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_1909">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_0050687"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:label>melanoma</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:1909</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#TopNodes_DOcancerslim"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4359">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_14566">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:label>disease of cellular proliferation</rdfs:label>
	<hasAlternativeId xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:0000818</hasAlternativeId>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">neoplasm</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">cell process disease</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:14566</id>
	<inSubset xmlns="http://www.geneontology.org/formats/oboInOwl#" rdf:resource="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim"/>
</rdf:Description>

</rdf:RDF>
(Score: 0.7827) <?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	xmlns:rdf4j="http://rdf4j.org/schema/rdf4j#"
	xmlns:sesame="http://www.openrdf.org/schema/sesame#"
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
	xmlns:fn="http://www.w3.org/2005/xpath-functions#">

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4360">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:label>disease</rdfs:label>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>
	<id xmlns="http://www.geneontology.org/formats/oboInOwl#">DOID:4</id>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_4360">
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_162"/>
</rdf:Description>

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/DOID_162">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_4"/>
	<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_14566"/>
	<rdfs:comment>Updating out dated UMLS CUI.</rdfs:comment>
	<rdfs:label>cancer</rdfs:label>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant neoplasm</hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">malignant tumor </hasExactSynonym>
	<hasExactSynonym xmlns="http://www.geneontology.org/formats/oboInOwl#">primary cancer</hasExactSynonym>
	<hasOBONamespace xmlns="http://www.geneontology.org/formats/oboInOwl#">disease_ontology</hasOBONamespace>

## Another Test

In [ ]:
top_k = min(5, len(corpus))
for query in queries:
    query_embedding = embedder.encode_query(query, convert_to_tensor=True)

    # We use cosine-similarity and torch.topk to find the highest 5 scores
    similarity_scores = embedder.similarity(query_embedding, corpus_embeddings)[0]
    scores, indices = torch.topk(similarity_scores, k=top_k)

    print("\nQuery:", query)
    print("Top 5 most similar sentences in corpus:")

    for score, idx in zip(scores, indices):
        print(f"(Score: {score:.4f})", corpus[idx])

Query: How do artificial neural networks work?
Top 5 most similar sentences in corpus:
(Score: 0.5926) Neural networks are computing systems vaguely inspired by the biological neural networks that constitute animal brains.
(Score: 0.5288) Deep learning is part of a broader family of machine learning methods based on artificial neural networks with representation learning.
(Score: 0.4647) Machine learning is a field of study that gives computers the ability to learn without being explicitly programmed.
(Score: 0.1381) Mars rovers are robotic vehicles designed to travel on the surface of Mars to collect data and perform experiments.
(Score: 0.0912) Carbon capture technologies aim to collect CO2 emissions before they enter the atmosphere and store them underground.

Query: What technology is used for modern space exploration?
Top 5 most similar sentences in corpus:
(Score: 0.3754) Mars rovers are robotic vehicles designed to travel on the surface of Mars to collect data and perform experiments.
(Score: 0.3669) SpaceX's Starship is designed to be a fully reusable transportation system capable of carrying humans to Mars and beyond.
(Score: 0.3452) The James Webb Space Telescope is the largest optical telescope in space, designed to conduct infrared astronomy.
(Score: 0.2625) Renewable energy sources include solar, wind, hydro, and geothermal power that naturally replenish over time.
(Score: 0.2275) Carbon capture technologies aim to collect CO2 emissions before they enter the atmosphere and store them underground.

Query: How can we address climate change challenges?
Top 5 most similar sentences in corpus:
(Score: 0.3760) Global warming is the long-term heating of Earth's climate system observed since the pre-industrial period due to human activities.
(Score: 0.3144) Carbon capture technologies aim to collect CO2 emissions before they enter the atmosphere and store them underground.
(Score: 0.2948) Renewable energy sources include solar, wind, hydro, and geothermal power that naturally replenish over time.
(Score: 0.0420) Machine learning is a field of study that gives computers the ability to learn without being explicitly programmed.
(Score: 0.0411) Deep learning is part of a broader family of machine learning methods based on artificial neural networks with representation learning.

Query: What is Machine Learning?
Top 5 most similar sentences in corpus:
(Score: 0.8559) Machine learning is a field of study that gives computers the ability to learn without being explicitly programmed.
(Score: 0.4927) Deep learning is part of a broader family of machine learning methods based on artificial neural networks with representation learning.
(Score: 0.3906) Neural networks are computing systems vaguely inspired by the biological neural networks that constitute animal brains.
(Score: 0.1935) Mars rovers are robotic vehicles designed to travel on the surface of Mars to collect data and perform experiments.
(Score: 0.1905) Global warming is the long-term heating of Earth's climate system observed since the pre-industrial period due to human activities.

# Full Test

In [ ]:
!pip -q install oxrdflib

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 13.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.2/587.2 kB 55.8 MB/s eta 0:00:00

In [ ]:
from rdflib import Graph
import pprint
import rdflib
import csv
import pandas as pd

In [ ]:
import requests
import zipfile
import io

url = "https://zenodo.org/records/13119437/files/ncit-doid.zip?download=1"
r = requests.get(url)
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall("data")

In [ ]:
datasetGraphDoid = Graph(store="Oxigraph")
datasetGraphNcit = Graph(store="Oxigraph")
datasetGraphDoid.parse("/content/data/ncit-doid/doid.owl", format="ox-xml")
datasetGraphNcit.parse("/content/data/ncit-doid/ncit.owl", format="ox-xml")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:

def query_sparql(queryText:str, graphToQuery:Graph)->rdflib.query.Result:
    return graphToQuery.query(queryText)

In [ ]:
#Verified test at the end. The documents affirm it runs SPAQRL 1.1, but it does not resolve the group_concat expressions, returning none
sparql_query = """
      PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      PREFIX owl: <http://www.w3.org/2002/07/owl#>
      PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?e (group_concat (CONCAT(str(?p), " ",str(?o)) ; separator="FIM") as ?contextLvl0) (group_concat (CONCAT(str(?o), " ", str(?p1), " ",str(?o1)) ; separator="FIM") as ?contextLvl1)
      WHERE {
          ?e ?p ?o.
    	    ?o ?p1 ?o1.
          {
            SELECT DISTINCT ?e
            WHERE {
                ?e rdf:type owl:Class.

            }
          }
      }group by ?e limit 2
      """
query_results = datasetGraphNcit.query(sparql_query)

#dFrame = pd.DataFrame(columns=['entity','contextLevl0','contextLevl1'])


for row in query_results:

  print(row)
  #nRow = {'entity':row.e, 'contextLevl0':row.contextLvl0, 'contextLevl1':row.contextLvl1}
  #print(nRow)
  #dFrame = pd.concat([dFrame, pd.DataFrame([nRow])])

(rdflib.term.URIRef('http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C6016'), None, None)
(rdflib.term.URIRef('http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C39950'), None, None)

In [ ]:
corpus

NameError: name 'corpus' is not defined

In [ ]:
import pandas as pd
import rdflib
from collections import defaultdict

# generate_dataframe: uses simple SPARQL (rdflib-compatible) and groups results in Python
def generate_dataframe(datasetOnto: rdflib.graph.Graph, show_progress: bool = False, max_rows: int | None = None) -> pd.DataFrame:
    """
    Query structure expected by this function (rdflib SPARQL):
      PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      PREFIX owl: <http://www.w3.org/2002/07/owl#>
      PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
      SELECT ?e ?p ?o ?p1 ?o1
      WHERE {
          ?e rdf:type owl:Class.
          ?e ?p ?o.
          ?o ?p1 ?o1.
      }
    """
    sparql = """
      PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      PREFIX owl: <http://www.w3.org/2002/07/owl#>
      PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
      SELECT ?e ?p ?o ?p1 ?o1
      WHERE {
          ?e rdf:type owl:Class.
          ?e ?p ?o.
          ?o ?p1 ?o1.
      }
    """
    qres = datasetOnto.query(sparql)
    # optional progress wrapper (tqdm) - non-fatal if tqdm not installed
    iterator = qres
    if show_progress:
        try:
            import tqdm
            iterator = tqdm.tqdm(qres)
        except Exception:
            iterator = qres
    acc = defaultdict(lambda: {'entity': None, 'contextLevl0': [], 'contextLevl1': []})
    count = 0
    for row in iterator:
        # safe conversions (avoid None errors and expensive str() calls until needed)
        e = str(row.e) if row.e is not None else ''
        p = str(row.p) if getattr(row, 'p', None) is not None else ''
        o = str(row.o) if getattr(row, 'o', None) is not None else ''
        p1 = str(row.p1) if getattr(row, 'p1', None) is not None else ''
        o1 = str(row.o1) if getattr(row, 'o1', None) is not None else ''
        acc[e]['entity'] = e
        acc[e]['contextLevl0'].append(p + '\t' + o + '\n')
        acc[e]['contextLevl1'].append(o + '\t' + p1 + '\t' + o1)
        count += 1
        if max_rows is not None and count >= max_rows:
            break
    # build DataFrame once from accumulated data
    rows = []
    for e, vals in acc.items():
        rows.append({
            'entity': vals['entity'],
            'contextLevl0': ''.join(vals['contextLevl0']),
            'contextLevl1': 'FIM'.join(vals['contextLevl1'])
        })
    return pd.DataFrame.from_records(rows, columns=['entity', 'contextLevl0', 'contextLevl1'])

# generate both dataframes (no progress by default)
dFrameOrigin = generate_dataframe(datasetGraphNcit).reset_index(drop=True)
dFrameTarget = generate_dataframe(datasetGraphDoid).reset_index(drop=True)

In [ ]:
dFrameOrigin["Candidates"]=""

In [ ]:
dFrameOrigin

,entity,contextLevl0,contextLevl1,Candidates
0,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,
1,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,
2,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,
3,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,
4,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,
...,...,...,...,...
23779,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,
23780,d623983ffbd1c9eb73d3e269f723c158,http://www.w3.org/2002/07/owl#intersectionOf\t...,cd1bb4e278157c8b83f8cd3541f120da\thttp://www.w...,
23781,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://www.w3.org/2002/07/owl#equivalentClass\...,d623983ffbd1c9eb73d3e269f723c158\thttp://www.w...,
23782,ed0f7be1999a3412afe391479e55356d,http://www.w3.org/2002/07/owl#intersectionOf\t...,b771d242303d503cb081ac6bef4af208\thttp://www.w...,
23783,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://www.w3.org/2002/07/owl#equivalentClass\...,ed0f7be1999a3412afe391479e55356d\thttp://www.w...,

In [ ]:
groupedOrigin_df = dFrameOrigin.groupby("entity").agg(
    contextLevl0=('contextLevl0', lambda x: " ".join(x.dropna())),
    contextLevl1=('contextLevl1', lambda x: " ".join(x.dropna()))
).reset_index()

In [ ]:
groupedTarget_df = dFrameTarget.groupby("entity").agg(
    contextLevl0=('contextLevl0', lambda x: " ".join(x.dropna())),
    contextLevl1=('contextLevl1', lambda x: " ".join(x.dropna()))
).reset_index()

In [ ]:
groupedOrigin_df.to_csv("dataset_output_groupedOrigin.csv", index=False)

In [ ]:
groupedTarget_df.to_csv("dataset_output_groupedTarget.csv", index=False)

In [ ]:
groupedOrigin_df

,entity,contextLevl0,contextLevl1
0,a00053e87595d06de3e286518388ace5,http://www.w3.org/2002/07/owl#intersectionOf\t...,e1b4fa129477c494b6bf960c3c97fe\thttp://www.w3....
1,a000c2fa2b275515a15ab84f84743937,http://www.w3.org/2002/07/owl#intersectionOf\t...,d97a95036c09e54872118b7512f86d27\thttp://www.w...
2,a002331e758da4629997305a4d99bf2,http://www.w3.org/2002/07/owl#intersectionOf\t...,cf5bd565a17270f2a30d2af722d5e548\thttp://www.w...
3,a00c78b565a24f032c5865478d7fc36,http://www.w3.org/2002/07/owl#intersectionOf\t...,ad7ab593c6dc19cefff40f8aa3ef4a81\thttp://www.w...
4,a00dd1272c1306703e0501d501ae9823,http://www.w3.org/2002/07/owl#intersectionOf\t...,bc14d6c16902faef92af2c9659f91d11\thttp://www.w...
...,...,...,...
23779,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
23780,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
23781,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
23782,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
23783,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...

In [ ]:
corpus = []

In [ ]:
for index, row in groupedOrigin_df.iterrows():
  corpus.append("The entity "+row["entity"]+" has context "+row["contextLevl0"]+" "+row["contextLevl1"])

In [ ]:
import pandas as pd
import random

# Load entities from SelSample.tsv
sel_sample_df = pd.read_csv("data/SelSample.tsv", sep="\t")
selected_entities = set(sel_sample_df["SrcEntity"].unique())

# Define the number of entities you want in the corpus
TARGET_CORPUS_SIZE = 1928  # Change this to your desired number

# Separate entities into two groups
selected_in_file = []
selected_not_in_file = []

In [ ]:
for index, row in groupedOrigin_df.iterrows():
    entity = row["entity"]
    text = "The entity "+row["entity"]+" has context "+row["contextLevl0"]+" "+row["contextLevl1"]

    if entity in selected_entities:
        selected_in_file.append(text)
    else:
        selected_not_in_file.append(text)

# Mix elements: prioritize selected entities, then add others to reach target size
corpus = selected_in_file.copy()

if len(corpus) < TARGET_CORPUS_SIZE:
    # Randomly sample from entities not in file to reach target size
    remaining_needed = TARGET_CORPUS_SIZE - len(corpus)
    additional = random.sample(selected_not_in_file, min(remaining_needed, len(selected_not_in_file)))
    corpus.extend(additional)

# If we still need more and we've exhausted non-selected entities, allow duplicate sampling
if len(corpus) < TARGET_CORPUS_SIZE and selected_not_in_file:
    remaining_needed = TARGET_CORPUS_SIZE - len(corpus)
    additional = random.choices(selected_not_in_file, k=remaining_needed)
    corpus.extend(additional)

print(f"Corpus size: {len(corpus)}")
print(f"Selected entities from file: {len(selected_in_file)}")
print(f"Additional entities added: {len(corpus) - len(selected_in_file)}")

Corpus size: 1928
Selected entities from file: 380
Additional entities added: 1548

In [ ]:
corpus[0]

'The entity http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C115993 has context http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\n http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://www.w3.org/2000/01/rdf-schema#label\tRetinal DisorderFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://oaei.ontologymatching.org/bio-ml/ann/use_in_alignment\tfalseFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P97\tAn abnormal structure or function of the retina and its associated tissues.FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P90\tRetinal DisorderFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P90\tRetinal DiseaseFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P371\tRetinal DisorderFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P366\tRetinal_DisorderFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P322\tNICHDFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P207\tC0035309FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P108\tRetinal DisorderFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P106\tDisease or SyndromeFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#NHC0\tC26875FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A8\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99147FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A8\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C90259FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A11\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26767FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://www.w3.org/2000/01/rdf-schema#subClassOf\td52f24751463334a7977fbbfa8a7db4bFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26767FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875\thttp://www.w3.org/1999/02/22-rdf-syntax-ns#type\thttp://www.w3.org/2002/07/owl#ClassFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\thttp://www.w3.org/2000/01/rdf-schema#label\tNon-Neoplastic Retinal DisorderFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\thttp://oaei.ontologymatching.org/bio-ml/ann/use_in_alignment\tfalseFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P90\tNon-Neoplastic Retinal DisorderFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P366\tNon-Neoplastic_Retinal_DisorderFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P207\tC1335039FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P108\tNon-Neoplastic Retinal DisorderFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P106\tDisease or SyndromeFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#NHC0\tC27610FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\thttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27604FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\thttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26875FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27610\thttp://www.w3.org/1999/02/22-rdf-syntax-ns#type\thttp://www.w3.org/2002/07/owl#Class'

In [ ]:
groupedOrigin_df

In [ ]:
corpusTarget = []

In [ ]:
for index, row in groupedTarget_df.iterrows():
  corpusTarget.append("The entity "+row["entity"]+" has context "+row["contextLevl0"]+" "+row["contextLevl1"])

In [ ]:
# Load target entities from SelSample.tsv
selected_target_entities = set(sel_sample_df["TgtEntity"].unique())

# Define the number of target entities you want in the corpus
TARGET_CORPUS_SIZE_TARGET = 686  # Change this to your desired number

# Separate target entities into two groups
selected_target_in_file = []
selected_target_not_in_file = []

In [ ]:
for index, row in groupedTarget_df.iterrows():
    entity = row["entity"]
    text = "The entity "+row["entity"]+" has context "+row["contextLevl0"]+" "+row["contextLevl1"]

    if entity in selected_target_entities:
        selected_target_in_file.append(text)
    else:
        selected_target_not_in_file.append(text)

# Mix elements: prioritize selected entities, then add others to reach target size
corpusTarget = selected_target_in_file.copy()

if len(corpusTarget) < TARGET_CORPUS_SIZE_TARGET:
    # Randomly sample from entities not in file to reach target size
    remaining_needed = TARGET_CORPUS_SIZE_TARGET - len(corpusTarget)
    additional = random.sample(selected_target_not_in_file, min(remaining_needed, len(selected_target_not_in_file)))
    corpusTarget.extend(additional)

# If we still need more and we've exhausted non-selected entities, allow duplicate sampling
if len(corpusTarget) < TARGET_CORPUS_SIZE_TARGET and selected_target_not_in_file:
    remaining_needed = TARGET_CORPUS_SIZE_TARGET - len(corpusTarget)
    additional = random.choices(selected_target_not_in_file, k=remaining_needed)
    corpusTarget.extend(additional)

print(f"Target Corpus size: {len(corpusTarget)}")
print(f"Selected target entities from file: {len(selected_target_in_file)}")
print(f"Additional target entities added: {len(corpusTarget) - len(selected_target_in_file)}")

Target Corpus size: 686
Selected target entities from file: 380
Additional target entities added: 306

In [ ]:
corpusTarget[0]

'The entity http://purl.obolibrary.org/obo/DOID_0050259 has context http://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_883\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_883\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_883\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_883\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_883\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_883\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_883\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_883\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_883\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_883\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_883\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_883\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_883\n http://purl.obolibrary.org/obo/DOID_883\thttp://www.w3.org/2000/01/rdf-schema#label\tparasitic helminthiasis infectious diseaseFIMhttp://purl.obolibrary.org/obo/DOID_883\thttp://www.geneontology.org/formats/oboInOwl#id\tDOID:883FIMhttp://purl.obolibrary.org/obo/DOID_883\thttp://www.geneontology.org/formats/oboInOwl#hasOBONamespace\tdisease_ontologyFIMhttp://purl.obolibrary.org/obo/DOID_883\thttp://www.geneontology.org/formats/oboInOwl#hasExactSynonym\tworm infectionFIMhttp://purl.obolibrary.org/obo/DOID_883\thttp://www.geneontology.org/formats/oboInOwl#hasExactSynonym\thelminthosisFIMhttp://purl.obolibrary.org/obo/DOID_883\thttp://www.geneontology.org/formats/oboInOwl#hasExactSynonym\thelminthiasisFIMhttp://purl.obolibrary.org/obo/DOID_883\thttp://www.geneontology.org/formats/oboInOwl#hasExactSynonym\thelminth infectionFIMhttp://purl.obolibrary.org/obo/DOID_883\thttp://www.geneontology.org/formats/oboInOwl#hasAlternativeId\tDOID:932FIMhttp://purl.obolibrary.org/obo/DOID_883\thttp://www.geneontology.org/formats/oboInOwl#hasAlternativeId\tDOID:458FIMhttp://purl.obolibrary.org/obo/DOID_883\thttp://www.geneontology.org/formats/oboInOwl#hasAlternativeId\tDOID:3563FIMhttp://purl.obolibrary.org/obo/DOID_883\thttp://www.geneontology.org/formats/oboInOwl#hasAlternativeId\tDOID:10693FIMhttp://purl.obolibrary.org/obo/DOID_883\thttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_1398FIMhttp://purl.obolibrary.org/obo/DOID_883\thttp://www.w3.org/1999/02/22-rdf-syntax-ns#type\thttp://www.w3.org/2002/07/owl#Class'

In [ ]:
!pip install sentence_transformers

Requirement already satisfied: sentence_transformers in /usr/local/lib/python3.12/dist-packages (5.2.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (4.57.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (2.9.0+cu126)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (1.16.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (0.36.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (3.20.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (2.32.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.5.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence_transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence_transformers) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence_transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (2026.1.4)

In [ ]:
"""
This is a simple application for sentence embeddings: semantic search

We have a corpus with various sentences. Then, for a given query sentence,
we want to find the most similar sentence in this corpus.

This script outputs for various queries the top 5 most similar sentences in the corpus.
"""

import torch

from sentence_transformers import SentenceTransformer

# Added trust_remote_code=True to allow loading the custom model architecture
embedder = SentenceTransformer("BAAI/bge-m3")
#embedder = SentenceTransformer("google/embeddinggemma-300m")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

In [ ]:
# Use "convert_to_tensor=True" to keep the tensors on GPU (if available)
# Changed 'encode_document' to 'encode' as SentenceTransformer uses 'encode'
corpus_embeddings = embedder.encode(corpus, convert_to_tensor=True)

In [ ]:
!pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.6 kB)
Requirement already satisfied: numpy<3.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (25.0)
Downloading faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (23.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 100.8 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.13.2

In [ ]:
import faiss
import numpy as np

index = faiss.IndexFlatL2(corpus_embeddings.shape[1])
index.add(corpus_embeddings)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
import faiss
import numpy as np
import torch  # only if corpus_embeddings is a torch.Tensor

# If corpus_embeddings is a PyTorch tensor on GPU:
embeddings_np = corpus_embeddings.detach().cpu().numpy().astype('float32')

# Create index and add vectors
d = embeddings_np.shape[1]
index = faiss.IndexFlatL2(d)
index.add(embeddings_np)

In [ ]:
import numpy as np

np.save("/content/drive/MyDrive/embeddings.npy", corpus_embeddings.detach().cpu().numpy().astype('float32'))

In [ ]:
import numpy as np

corpus_embeddings = np.load("embeddings.npy")

FileNotFoundError: [Errno 2] No such file or directory: 'embeddings.npy'

In [ ]:
embeddings_np = np.load("embeddings.npy")
device = "cuda" if torch.cuda.is_available() else "cpu"
corpus_embeddings = torch.from_numpy(embeddings_np).to(device) # dtype float32

In [ ]:
results = []

In [ ]:
from sentence_transformers import util
import torch

# Ensure corpus_embeddings is on the correct device (same as the model)
device = embedder.device
if not isinstance(corpus_embeddings, torch.Tensor):
    corpus_embeddings = torch.tensor(corpus_embeddings)
corpus_embeddings = corpus_embeddings.to(device)

count = 0
# Find the closest 10 sentences of the corpus for each query sentence based on cosine similarity
top_k = min(10, len(corpus))

for query in corpusTarget:
    query_embedding = embedder.encode_query(query, convert_to_tensor=True)

    # We use cosine-similarity and torch.topk to find the highest 5 scores
    similarity_scores = embedder.similarity(query_embedding, corpus_embeddings)[0]
    scores, indices = torch.topk(similarity_scores, k=top_k)

    # Use a fresh list for each query instead of accumulating in a global topK
    current_top_k = []
    for score, idx in zip(scores, indices):
        # Use .item() to convert 0-d tensor to int for list indexing
        current_top_k.append(corpus[idx.item()])

    results.append([f"\nQuery:{query}. Top 5 most similar ", current_top_k])

    count += 1
    print(f"Row {count} of {len(corpusTarget)}")

Row 1 of 686
Row 2 of 686
Row 3 of 686
Row 4 of 686
Row 5 of 686
Row 6 of 686
Row 7 of 686
Row 8 of 686
Row 9 of 686
Row 10 of 686
Row 11 of 686
Row 12 of 686
Row 13 of 686
Row 14 of 686
Row 15 of 686
Row 16 of 686
Row 17 of 686
Row 18 of 686
Row 19 of 686
Row 20 of 686
Row 21 of 686
Row 22 of 686
Row 23 of 686
Row 24 of 686
Row 25 of 686
Row 26 of 686
Row 27 of 686
Row 28 of 686
Row 29 of 686
Row 30 of 686
Row 31 of 686
Row 32 of 686
Row 33 of 686
Row 34 of 686
Row 35 of 686
Row 36 of 686
Row 37 of 686
Row 38 of 686
Row 39 of 686
Row 40 of 686
Row 41 of 686
Row 42 of 686
Row 43 of 686
Row 44 of 686
Row 45 of 686
Row 46 of 686
Row 47 of 686
Row 48 of 686
Row 49 of 686
Row 50 of 686
Row 51 of 686
Row 52 of 686
Row 53 of 686
Row 54 of 686
Row 55 of 686
Row 56 of 686
Row 57 of 686
Row 58 of 686
Row 59 of 686
Row 60 of 686
Row 61 of 686
Row 62 of 686
Row 63 of 686
Row 64 of 686
Row 65 of 686
Row 66 of 686
Row 67 of 686
Row 68 of 686
Row 69 of 686
Row 70 of 686
Row 71 of 686
Row 72 of 686
Row 73 of 686
Row 74 of 686
Row 75 of 686
Row 76 of 686
Row 77 of 686
Row 78 of 686
Row 79 of 686
Row 80 of 686
Row 81 of 686
Row 82 of 686
Row 83 of 686
Row 84 of 686
Row 85 of 686
Row 86 of 686
Row 87 of 686
Row 88 of 686
Row 89 of 686
Row 90 of 686
Row 91 of 686
Row 92 of 686
Row 93 of 686
Row 94 of 686
Row 95 of 686
Row 96 of 686
Row 97 of 686
Row 98 of 686
Row 99 of 686
Row 100 of 686
Row 101 of 686
Row 102 of 686
Row 103 of 686
Row 104 of 686
Row 105 of 686
Row 106 of 686
Row 107 of 686
Row 108 of 686
Row 109 of 686
Row 110 of 686
Row 111 of 686
Row 112 of 686
Row 113 of 686
Row 114 of 686
Row 115 of 686
Row 116 of 686
Row 117 of 686
Row 118 of 686
Row 119 of 686
Row 120 of 686
Row 121 of 686
Row 122 of 686
Row 123 of 686
Row 124 of 686
Row 125 of 686
Row 126 of 686
Row 127 of 686
Row 128 of 686
Row 129 of 686
Row 130 of 686
Row 131 of 686
Row 132 of 686
Row 133 of 686
Row 134 of 686
Row 135 of 686
Row 136 of 686
Row 137 of 686
Row 138 of 686
Row 139 of 686
Row 140 of 686
Row 141 of 686
Row 142 of 686
Row 143 of 686
Row 144 of 686
Row 145 of 686
Row 146 of 686
Row 147 of 686
Row 148 of 686
Row 149 of 686
Row 150 of 686
Row 151 of 686
Row 152 of 686
Row 153 of 686
Row 154 of 686
Row 155 of 686
Row 156 of 686
Row 157 of 686
Row 158 of 686
Row 159 of 686
Row 160 of 686
Row 161 of 686
Row 162 of 686
Row 163 of 686
Row 164 of 686
Row 165 of 686
Row 166 of 686
Row 167 of 686
Row 168 of 686
Row 169 of 686
Row 170 of 686
Row 171 of 686
Row 172 of 686
Row 173 of 686
Row 174 of 686
Row 175 of 686
Row 176 of 686
Row 177 of 686
Row 178 of 686
Row 179 of 686
Row 180 of 686
Row 181 of 686
Row 182 of 686
Row 183 of 686
Row 184 of 686
Row 185 of 686
Row 186 of 686
Row 187 of 686
Row 188 of 686
Row 189 of 686
Row 190 of 686
Row 191 of 686
Row 192 of 686
Row 193 of 686
Row 194 of 686
Row 195 of 686
Row 196 of 686
Row 197 of 686
Row 198 of 686
Row 199 of 686
Row 200 of 686
Row 201 of 686
Row 202 of 686
Row 203 of 686
Row 204 of 686
Row 205 of 686
Row 206 of 686
Row 207 of 686
Row 208 of 686
Row 209 of 686
Row 210 of 686
Row 211 of 686
Row 212 of 686
Row 213 of 686
Row 214 of 686
Row 215 of 686
Row 216 of 686
Row 217 of 686
Row 218 of 686
Row 219 of 686
Row 220 of 686
Row 221 of 686
Row 222 of 686
Row 223 of 686
Row 224 of 686
Row 225 of 686
Row 226 of 686
Row 227 of 686
Row 228 of 686
Row 229 of 686
Row 230 of 686
Row 231 of 686
Row 232 of 686
Row 233 of 686
Row 234 of 686
Row 235 of 686
Row 236 of 686
Row 237 of 686
Row 238 of 686
Row 239 of 686
Row 240 of 686
Row 241 of 686
Row 242 of 686
Row 243 of 686
Row 244 of 686
Row 245 of 686
Row 246 of 686
Row 247 of 686
Row 248 of 686
Row 249 of 686
Row 250 of 686
Row 251 of 686
Row 252 of 686
Row 253 of 686
Row 254 of 686
Row 255 of 686
Row 256 of 686
Row 257 of 686
Row 258 of 686
Row 259 of 686
Row 260 of 686
Row 261 of 686
Row 262 of 686
Row 263 of 686
Row 264 of 686
Row 265 of 686
Row 266 of 686
Row 267 of 686
Row 268 of 686
Row 269 of 686
Row 270 of 686
Row 271 of 686
Row 272 of 686
Row 273 of 686
Row 274 of 686
Row 275 of 686
Row 276 of 686
Row 277 of 686
Row 278 of 686
Row 279 of 686
Row 280 of 686
Row 281 of 686
Row 282 of 686
Row 283 of 686
Row 284 of 686
Row 285 of 686
Row 286 of 686
Row 287 of 686
Row 288 of 686
Row 289 of 686
Row 290 of 686
Row 291 of 686
Row 292 of 686
Row 293 of 686
Row 294 of 686
Row 295 of 686
Row 296 of 686
Row 297 of 686
Row 298 of 686
Row 299 of 686
Row 300 of 686
Row 301 of 686
Row 302 of 686
Row 303 of 686
Row 304 of 686
Row 305 of 686
Row 306 of 686
Row 307 of 686
Row 308 of 686
Row 309 of 686
Row 310 of 686
Row 311 of 686
Row 312 of 686
Row 313 of 686
Row 314 of 686
Row 315 of 686
Row 316 of 686
Row 317 of 686
Row 318 of 686
Row 319 of 686
Row 320 of 686
Row 321 of 686
Row 322 of 686
Row 323 of 686
Row 324 of 686
Row 325 of 686
Row 326 of 686
Row 327 of 686
Row 328 of 686
Row 329 of 686
Row 330 of 686
Row 331 of 686
Row 332 of 686
Row 333 of 686
Row 334 of 686
Row 335 of 686
Row 336 of 686
Row 337 of 686
Row 338 of 686
Row 339 of 686
Row 340 of 686
Row 341 of 686
Row 342 of 686
Row 343 of 686
Row 344 of 686
Row 345 of 686
Row 346 of 686
Row 347 of 686
Row 348 of 686
Row 349 of 686
Row 350 of 686
Row 351 of 686
Row 352 of 686
Row 353 of 686
Row 354 of 686
Row 355 of 686
Row 356 of 686
Row 357 of 686
Row 358 of 686
Row 359 of 686
Row 360 of 686
Row 361 of 686
Row 362 of 686
Row 363 of 686
Row 364 of 686
Row 365 of 686
Row 366 of 686
Row 367 of 686
Row 368 of 686
Row 369 of 686
Row 370 of 686
Row 371 of 686
Row 372 of 686
Row 373 of 686
Row 374 of 686
Row 375 of 686
Row 376 of 686
Row 377 of 686
Row 378 of 686
Row 379 of 686
Row 380 of 686
Row 381 of 686
Row 382 of 686
Row 383 of 686
Row 384 of 686
Row 385 of 686
Row 386 of 686
Row 387 of 686
Row 388 of 686
Row 389 of 686
Row 390 of 686
Row 391 of 686
Row 392 of 686
Row 393 of 686
Row 394 of 686
Row 395 of 686
Row 396 of 686
Row 397 of 686
Row 398 of 686
Row 399 of 686
Row 400 of 686
Row 401 of 686
Row 402 of 686
Row 403 of 686
Row 404 of 686
Row 405 of 686
Row 406 of 686
Row 407 of 686
Row 408 of 686
Row 409 of 686
Row 410 of 686
Row 411 of 686
Row 412 of 686
Row 413 of 686
Row 414 of 686
Row 415 of 686
Row 416 of 686
Row 417 of 686
Row 418 of 686
Row 419 of 686
Row 420 of 686
Row 421 of 686
Row 422 of 686
Row 423 of 686
Row 424 of 686
Row 425 of 686
Row 426 of 686
Row 427 of 686
Row 428 of 686
Row 429 of 686
Row 430 of 686
Row 431 of 686
Row 432 of 686
Row 433 of 686
Row 434 of 686
Row 435 of 686
Row 436 of 686
Row 437 of 686
Row 438 of 686
Row 439 of 686
Row 440 of 686
Row 441 of 686
Row 442 of 686
Row 443 of 686
Row 444 of 686
Row 445 of 686
Row 446 of 686
Row 447 of 686
Row 448 of 686
Row 449 of 686
Row 450 of 686
Row 451 of 686
Row 452 of 686
Row 453 of 686
Row 454 of 686
Row 455 of 686
Row 456 of 686
Row 457 of 686
Row 458 of 686
Row 459 of 686
Row 460 of 686
Row 461 of 686
Row 462 of 686
Row 463 of 686
Row 464 of 686
Row 465 of 686
Row 466 of 686
Row 467 of 686
Row 468 of 686
Row 469 of 686
Row 470 of 686
Row 471 of 686
Row 472 of 686
Row 473 of 686
Row 474 of 686
Row 475 of 686
Row 476 of 686
Row 477 of 686
Row 478 of 686
Row 479 of 686
Row 480 of 686
Row 481 of 686
Row 482 of 686
Row 483 of 686
Row 484 of 686
Row 485 of 686
Row 486 of 686
Row 487 of 686
Row 488 of 686
Row 489 of 686
Row 490 of 686
Row 491 of 686
Row 492 of 686
Row 493 of 686
Row 494 of 686
Row 495 of 686
Row 496 of 686
Row 497 of 686
Row 498 of 686
Row 499 of 686
Row 500 of 686
Row 501 of 686
Row 502 of 686
Row 503 of 686
Row 504 of 686
Row 505 of 686
Row 506 of 686
Row 507 of 686
Row 508 of 686
Row 509 of 686
Row 510 of 686
Row 511 of 686
Row 512 of 686
Row 513 of 686
Row 514 of 686
Row 515 of 686
Row 516 of 686
Row 517 of 686
Row 518 of 686
Row 519 of 686
Row 520 of 686
Row 521 of 686
Row 522 of 686
Row 523 of 686
Row 524 of 686
Row 525 of 686
Row 526 of 686
Row 527 of 686
Row 528 of 686
Row 529 of 686
Row 530 of 686
Row 531 of 686
Row 532 of 686
Row 533 of 686
Row 534 of 686
Row 535 of 686
Row 536 of 686
Row 537 of 686
Row 538 of 686
Row 539 of 686
Row 540 of 686
Row 541 of 686
Row 542 of 686
Row 543 of 686
Row 544 of 686
Row 545 of 686
Row 546 of 686
Row 547 of 686
Row 548 of 686
Row 549 of 686
Row 550 of 686
Row 551 of 686
Row 552 of 686
Row 553 of 686
Row 554 of 686
Row 555 of 686
Row 556 of 686
Row 557 of 686
Row 558 of 686
Row 559 of 686
Row 560 of 686
Row 561 of 686
Row 562 of 686
Row 563 of 686
Row 564 of 686
Row 565 of 686
Row 566 of 686
Row 567 of 686
Row 568 of 686
Row 569 of 686
Row 570 of 686
Row 571 of 686
Row 572 of 686
Row 573 of 686
Row 574 of 686
Row 575 of 686
Row 576 of 686
Row 577 of 686
Row 578 of 686
Row 579 of 686
Row 580 of 686
Row 581 of 686
Row 582 of 686
Row 583 of 686
Row 584 of 686
Row 585 of 686
Row 586 of 686
Row 587 of 686
Row 588 of 686
Row 589 of 686
Row 590 of 686
Row 591 of 686
Row 592 of 686
Row 593 of 686
Row 594 of 686
Row 595 of 686
Row 596 of 686
Row 597 of 686
Row 598 of 686
Row 599 of 686
Row 600 of 686
Row 601 of 686
Row 602 of 686
Row 603 of 686
Row 604 of 686
Row 605 of 686
Row 606 of 686
Row 607 of 686
Row 608 of 686
Row 609 of 686
Row 610 of 686
Row 611 of 686
Row 612 of 686
Row 613 of 686
Row 614 of 686
Row 615 of 686
Row 616 of 686
Row 617 of 686
Row 618 of 686
Row 619 of 686
Row 620 of 686
Row 621 of 686
Row 622 of 686
Row 623 of 686
Row 624 of 686
Row 625 of 686
Row 626 of 686
Row 627 of 686
Row 628 of 686
Row 629 of 686
Row 630 of 686
Row 631 of 686
Row 632 of 686
Row 633 of 686
Row 634 of 686
Row 635 of 686
Row 636 of 686
Row 637 of 686
Row 638 of 686
Row 639 of 686
Row 640 of 686
Row 641 of 686
Row 642 of 686
Row 643 of 686
Row 644 of 686
Row 645 of 686
Row 646 of 686
Row 647 of 686
Row 648 of 686
Row 649 of 686
Row 650 of 686
Row 651 of 686
Row 652 of 686
Row 653 of 686
Row 654 of 686
Row 655 of 686
Row 656 of 686
Row 657 of 686
Row 658 of 686
Row 659 of 686
Row 660 of 686
Row 661 of 686
Row 662 of 686
Row 663 of 686
Row 664 of 686
Row 665 of 686
Row 666 of 686
Row 667 of 686
Row 668 of 686
Row 669 of 686
Row 670 of 686
Row 671 of 686
Row 672 of 686
Row 673 of 686
Row 674 of 686
Row 675 of 686
Row 676 of 686
Row 677 of 686
Row 678 of 686
Row 679 of 686
Row 680 of 686
Row 681 of 686
Row 682 of 686
Row 683 of 686
Row 684 of 686
Row 685 of 686
Row 686 of 686

In [ ]:
import pickle
with open("/content/drive/MyDrive/items.pkl", "wb") as f:
  pickle.dump(results, f)

In [ ]:
from google.colab import drive


drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pickle
with open("items.pkl", "rb") as f:
  results = pickle.load(f)

In [ ]:
import pickle
with open("/content/drive/MyDrive/items.pkl", "rb") as f:
  results = pickle.load(f)

In [ ]:
results[8]

['\nQuery:The entity http://purl.obolibrary.org/obo/DOID_0050568 has context http://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_1934\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_1934\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_1934\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_1934\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_1934\n http://purl.obolibrary.org/obo/DOID_1934\thttp://www.w3.org/2000/01/rdf-schema#label\tdysostosisFIMhttp://purl.obolibrary.org/obo/DOID_1934\thttp://www.geneontology.org/formats/oboInOwl#id\tDOID:1934FIMhttp://purl.obolibrary.org/obo/DOID_1934\thttp://www.geneontology.org/formats/oboInOwl#hasOBONamespace\tdisease_ontologyFIMhttp://purl.obolibrary.org/obo/DOID_1934\thttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://purl.obolibrary.org/obo/DOID_0080006FIMhttp://purl.obolibrary.org/obo/DOID_1934\thttp://www.w3.org/1999/02/22-rdf-syntax-ns#type\thttp://www.w3.org/2002/07/owl#Class. Top 5 most similar ',
 ['The entity http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C125598 has context http://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\n http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\thttp://www.w3.org/2000/01/rdf-schema#label\tDysostosisFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P97\tA defect in ossification of bone.FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P90\tDysostosisFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P366\tDysostosisFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P207\tC0013393FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P108\tDysostosisFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P106\tDisease or SyndromeFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#NHC0\tC34560FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\thttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27572FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34560\thttp://www.w3.org/1999/02/22-rdf-syntax-ns#type\thttp://www.w3.org/2002/07/owl#Class',
  'The entity http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C37058 has context http://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\n http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\thttp://www.w3.org/2000/01/rdf-schema#label\tSideroblastFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\thttp://oaei.ontologymatching.org/bio-ml/ann/use_in_alignment\tfalseFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P90\tSideroblastFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P366\tSideroblastFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P207\tC0229630FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P108\tSideroblastFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P106\tCellFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#NHC0\tC36718FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\thttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C37057FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36718\thttp://www.w3.org/1999/02/22-rdf-syntax-ns#type\thttp://www.w3.org/2002/07/owl#Class',
  'The entity http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34545 has context http://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\n http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\thttp://www.w3.org/2000/01/rdf-schema#label\tHead and Neck InfectionFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\thttp://oaei.ontologymatching.org/bio-ml/ann/use_in_alignment\tfalseFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P90\tHead and Neck InfectionFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P366\tHead_and_Neck_InfectionFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P207\tC1333943FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P108\tHead and Neck InfectionFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P106\tDisease or SyndromeFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#NHC0\tC35733FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\thttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27583FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35733\thttp://www.w3.org/1999/02/22-rdf-syntax-ns#type\thttp://www.w3.org/2002/07/owl#Class',
  'The entity http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41048 has context http://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\n http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\thttp://www.w3.org/2000/01/rdf-schema#label\tImmunoglobulin DepositionFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\thttp://oaei.ontologymatching.org/bio-ml/ann/use_in_alignment\tfalseFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P90\tImmunoglobulin DepositionFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P366\tImmunoglobulin_DepositionFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P207\tC1512663FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P108\tImmunoglobulin DepositionFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P106\tFindingFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#NHC0\tC41042FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\thttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C9442FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41042\thttp://www.w3.org/1999/02/22-rdf-syntax-ns#type\thttp://www.w3.org/2002/07/owl#Class',
  'The entity http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34713 has context http://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\n http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\thttp://www.w3.org/2000/01/rdf-schema#label\tHyperostosisFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P97\tExcessive thickening of bone.FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P90\tHyperostosisFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P90\tBone HypertrophyFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P366\tHyperostosisFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P207\tC0020492FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P108\tHyperostosisFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P106\tDisease or SyndromeFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#NHC0\tC34712FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\thttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27572FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34712\thttp://www.w3.org/1999/02/22-rdf-syntax-ns#type\thttp://www.w3.org/2002/07/owl#Class',
  'The entity http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36558 has context http://www.w3.org/2000/01/rdf-schema#subClassOf\ta4f999eca519072ce0a31d1c3e3578f3\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\ta4f999eca519072ce0a31d1c3e3578f3\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\ta4f999eca519072ce0a31d1c3e3578f3\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\nhttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\n a4f999eca519072ce0a31d1c3e3578f3\thttp://www.w3.org/2002/07/owl#someValuesFrom\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C13204FIMa4f999eca519072ce0a31d1c3e3578f3\thttp://www.w3.org/2002/07/owl#onProperty\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#R173FIMa4f999eca519072ce0a31d1c3e3578f3\thttp://www.w3.org/1999/02/22-rdf-syntax-ns#type\thttp://www.w3.org/2002/07/owl#RestrictionFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\thttp://www.w3.org/2000/01/rdf-schema#label\tChromosomal GainFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\thttp://oaei.ontologymatching.org/bio-ml/ann/use_in_alignment\tfalseFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P90\tChromosomal GainFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P366\tChromosomal_GainFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P207\tC1516517FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P108\tChromosomal GainFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P106\tCell or Molecular DysfunctionFIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#NHC0\tC36438FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\thttp://www.w3.org/2000/01/rdf-schema#subClassOf\thttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C6825FIMhttp://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36438\thttp://www.w3.org/1999/02/22-rdf-syntax-ns#type\thttp://www.w3.org/2002/07/owl#Class',

In [ ]:
search_string = "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C3088"

if search_string in results[0]:
    print(f"'{search_string}' was found!")
else:
    print(f"'{search_string}' was not found.")

'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C3088' was not found.

In [ ]:
file_path = '/content/data/ncit-doid/refs_equiv/full.tsv'

dFrameVerify = pd.read_csv(file_path, sep='\t')

In [ ]:
dFrameVerify.head()

,SrcEntity,TgtEntity,Score
0,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://purl.obolibrary.org/obo/DOID_4362,1.0
1,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://purl.obolibrary.org/obo/DOID_4364,1.0
2,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://purl.obolibrary.org/obo/DOID_438,1.0
3,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://purl.obolibrary.org/obo/DOID_4353,1.0
4,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://purl.obolibrary.org/obo/DOID_4359,1.0

In [ ]:
validEl = []

In [ ]:


for index, row in dFrameVerify.iterrows():

  row['SrcEntity']

In [ ]:
if dFrameVerify.TgtEntity[2] in results:
  print("yes")
else:
  print("no")

no

In [ ]:
dFrameVerify.TgtEntity[0]

'http://purl.obolibrary.org/obo/DOID_4362'

# Evaluation

In [ ]:
import pandas as pd # Ensure pandas is imported if this cell is run independently
import pickle
import re
from collections import defaultdict # Needed for the new mapping structure

try:
    results
except NameError:
    # Load from pickle file
    with open("items.pkl", "rb") as f:
        results = pickle.load(f)

# First, let's inspect the structure of results
print(f"Results type: {type(results)}")
print(f"Results length: {len(results)}")
print("\nFirst item structure:")
print(f"Type: {type(results[0])}")
print(f"Length: {len(results[0])}")
print(f"\nFirst element (query string) preview (first 200 chars):")
print(results[0][0][:200] if results[0][0] else "NONE")
print(f"\nSecond element (candidates) type: {type(results[0][1])}")
print(f"Second element (candidates) length: {len(results[0][1]) if isinstance(results[0][1], list) else 'N/A'}")
if isinstance(results[0][1], list) and len(results[0][1]) > 0:
    print(f"First candidate: {results[0][1][0][:100] if isinstance(results[0][1][0], str) else results[0][1][0]}")

def extract_entity_from_string(text_string):
    """
    Extract entity URI or BNode ID from a text string.
    Expected format: 'The entity <entity_identifier> has context ...'
    """
    match = re.search(r'The entity ([^\s]+)', text_string)
    if match:
        return match.group(1).strip()
    return None

def populate_target_column_in_dframe_origin(dframe_origin_df, similarity_results, target_column_name="aligned"):
    """
    Populate a specified column in dframe_origin_df based on similarity_results.
    dframe_origin_df: DataFrame containing NCIT entities.
    similarity_results: list of [DOID_query_string, [NCIT_candidate_strings]]
    target_column_name: The name of the column in dframe_origin_df to populate.
    """
    # Ensure the target column exists and is initialized with empty lists
    if target_column_name not in dframe_origin_df.columns:
        dframe_origin_df[target_column_name] = [[] for _ in range(len(dframe_origin_df))]
    else:
        # Re-initialize it to ensure it's empty for new population
        dframe_origin_df[target_column_name] = [[] for _ in range(len(dframe_origin_df))]

    # Create a temporary dictionary to store NCIT -> [DOID] alignments
    ncit_to_doid_alignments = defaultdict(list)

    processed_queries = 0
    skipped_queries = 0
    total_alignments_added = 0

    # Debugging print statements
    # print("--- Debug: Populating ncit_to_doid_alignments (first 3 candidates loop) ---")
    # candidate_loop_count = 0

    for item in similarity_results:
        if len(item) == 2:
            query_string = str(item[0])
            candidates_list = item[1] if isinstance(item[1], list) else []

            doid_entity = extract_entity_from_string(query_string)

            if doid_entity:
                processed_queries += 1
                for ncit_candidate_string in candidates_list:
                    ncit_entity = extract_entity_from_string(ncit_candidate_string)
                    if ncit_entity:
                        # if candidate_loop_count < 3:
                        #     print(f"  - Adding alignment: NCIT='{ncit_entity}' <= DOID='{doid_entity}'")
                        #     candidate_loop_count += 1
                        if doid_entity not in ncit_to_doid_alignments[ncit_entity]:
                            ncit_to_doid_alignments[ncit_entity].append(doid_entity)
                            total_alignments_added += 1
                    # else:
                        # print(f"  - Failed to extract NCIT entity from candidate string: {ncit_candidate_string[:100]}")
            # else:
                # print(f"  - Failed to extract DOID entity from query string: {query_string[:100]}")
                skipped_queries += 1
        # else:
            # print(f"  - Skipped item in similarity_results due to incorrect format: {item}")
            skipped_queries += 1

    # print(f"--- Debug: ncit_to_doid_alignments built. Total unique NCIT entities as keys: {len(ncit_to_doid_alignments)} ---")
    # if len(ncit_to_doid_alignments) > 0:
    #     first_key = next(iter(ncit_to_doid_alignments))
    #     print(f"First key in ncit_to_doid_alignments: '{first_key}' (type: {type(first_key)})")
    #     print(f"Sample value for first key: {ncit_to_doid_alignments[first_key][0]}")

    # print("\n--- Debug: Updating dframe_origin_df (first 3 lookups) ---")
    # df_update_count = 0
    for index, row in dframe_origin_df.iterrows():
        ncit_entity_uri_from_df = row['entity']
        # if df_update_count < 3:
        #     print(f"  - Looking up entity from dFrameOrigin: '{ncit_entity_uri_from_df}'")
        #     print(f"  - Is it in ncit_to_doid_alignments keys? {ncit_entity_uri_from_df in ncit_to_doid_alignments}")
        #     df_update_count += 1
        if ncit_entity_uri_from_df in ncit_to_doid_alignments:
            dframe_origin_df.at[index, target_column_name] = ncit_to_doid_alignments[ncit_entity_uri_from_df]

    # print("--- Debug: dframe_origin_df update loop finished ---")

    print(f"Processed {processed_queries} DOID queries, skipped {skipped_queries} queries due to parsing issues.")
    print(f"Total {total_alignments_added} unique DOID entities aligned as candidates to NCIT entities for column '{target_column_name}'.")

    return dframe_origin_df

# The function will be called in a subsequent cell to apply the changes.

Results type: <class 'list'>
Results length: 686

First item structure:
Type: <class 'list'>
Length: 2

First element (query string) preview (first 200 chars):

Query:The entity http://purl.obolibrary.org/obo/DOID_0050259 has context http://www.w3.org/2000/01/rdf-schema#subClassOf	http://purl.obolibrary.org/obo/DOID_883
http://www.w3.org/2000/01/rdf-schema#s

Second element (candidates) type: <class 'list'>
Second element (candidates) length: 10
First candidate: The entity http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34545 has context http://www.w3.org/2

In [ ]:
import pandas as pd

# Unconditionally drop the 'Candidates' column if it exists
if 'Candidates' in dFrameOrigin.columns:
    print("Unconditionally dropping 'Candidates' column.")
    dFrameOrigin = dFrameOrigin.drop(columns=['Candidates'])


# Verify if any entities have been aligned
num_aligned_entities = dFrameOrigin['aligned'].apply(lambda x: len(x) > 0).sum()

print(f"\nNumber of NCIT entities with at least one aligned DOID entity: {num_aligned_entities}")
if num_aligned_entities == 0:
    print("It seems no entities were aligned. This might indicate an issue with the entity extraction or matching logic.")
else:
    print("Alignments have been successfully added to the 'aligned' column for some entities.")

    # Find and display an example of a row with aligned entities
    aligned_example_row = dFrameOrigin[dFrameOrigin['aligned'].apply(lambda x: len(x) > 0)].iloc[0]
    print("\n--- Example of a successfully aligned row ---")
    print(f"NCIT Entity: {aligned_example_row['entity']}")
    print(f"Aligned DOID Entities: {aligned_example_row['aligned']}")
    print("--------------------------------------------")

# Display the final updated DataFrame head after all operations
print("\nFinal dFrameOrigin head after processing (first 5 rows):")
display(dFrameOrigin.head())

# Display a few rows that actually have aligned entities
if num_aligned_entities > 0:
    print("\nDisplaying a few rows from dFrameOrigin with populated 'aligned' lists:")
    display(dFrameOrigin[dFrameOrigin['aligned'].apply(lambda x: len(x) > 0)].head())

Unconditionally dropping 'Candidates' column.

KeyError: 'aligned'

In [ ]:
dFrameOrigin

,entity,contextLevl0,contextLevl1
0,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
1,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
2,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
3,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
4,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
...,...,...,...
23779,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
23780,dbab9531c0906c5838193bd780ca5f75,http://www.w3.org/2002/07/owl#intersectionOf\t...,ac068d9b0675a028c03bbe52726aa816\thttp://www.w...
23781,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://www.w3.org/2002/07/owl#equivalentClass\...,dbab9531c0906c5838193bd780ca5f75\thttp://www.w...
23782,bd41c7dbb9c77626c27b20db461cdae8,http://www.w3.org/2002/07/owl#intersectionOf\t...,f5b8a3d587ddab2fdb6aedefe6e3dfd7\thttp://www.w...
23783,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://www.w3.org/2002/07/owl#equivalentClass\...,bd41c7dbb9c77626c27b20db461cdae8\thttp://www.w...

In [ ]:
# Ensure 'Candidates' column exists and is initialized
if 'Candidates' not in dFrameOrigin.columns:
    dFrameOrigin['Candidates'] = [[] for _ in range(len(dFrameOrigin))]
else:
    dFrameOrigin['Candidates'] = [[] for _ in range(len(dFrameOrigin))] # Clear it if it already exists

# Populate the 'Candidates' column
dFrameOrigin = populate_target_column_in_dframe_origin(dFrameOrigin, results, target_column_name="Candidates")

# Ensure the 'aligned' column is empty
if 'aligned' not in dFrameOrigin.columns:
    dFrameOrigin['aligned'] = [[] for _ in range(len(dFrameOrigin))]
else:
    dFrameOrigin['aligned'] = [[] for _ in range(len(dFrameOrigin))]


print("\n======================================================================")
print("DataFrame dFrameOrigin after populating 'Candidates' and resetting 'aligned':")
print("======================================================================")
display(dFrameOrigin.head())

# Display a few rows that actually have populated 'Candidates' lists
num_candidates_populated = dFrameOrigin['Candidates'].apply(lambda x: len(x) > 0).sum()
if num_candidates_populated > 0:
    print("\nDisplaying a few rows from dFrameOrigin with populated 'Candidates' lists:")
    display(dFrameOrigin[dFrameOrigin['Candidates'].apply(lambda x: len(x) > 0)].head())
else:
    print("No 'Candidates' lists were populated. Please check the logic if this is unexpected.")

Processed 686 DOID queries, skipped 1372 queries due to parsing issues.
Total 6860 unique DOID entities aligned as candidates to NCIT entities for column 'Candidates'.

======================================================================
DataFrame dFrameOrigin after populating 'Candidates' and resetting 'aligned':
======================================================================

,entity,contextLevl0,contextLevl1,Candidates,aligned
0,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,[],[]
1,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,[],[]
2,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,[],[]
3,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,[],[]
4,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,[],[]

Displaying a few rows from dFrameOrigin with populated 'Candidates' lists:

,entity,contextLevl0,contextLevl1,Candidates,aligned
1066,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://www.w3.org/2000/01/rdf-schema#subClassO...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,[http://purl.obolibrary.org/obo/DOID_11328],[]
1067,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://www.w3.org/2000/01/rdf-schema#subClassO...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,"[http://purl.obolibrary.org/obo/DOID_0060167, ...",[]
1341,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://www.w3.org/2000/01/rdf-schema#subClassO...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,"[http://purl.obolibrary.org/obo/DOID_3444, htt...",[]
1390,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://www.w3.org/2000/01/rdf-schema#subClassO...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,"[http://purl.obolibrary.org/obo/DOID_4186, htt...",[]
1528,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://www.w3.org/2002/07/owl#equivalentClass\...,d3679cc83c1379ce8e9baa63878680a\thttp://www.w3...,"[http://purl.obolibrary.org/obo/DOID_3196, htt...",[]

In [ ]:
# First, ensure Ollama is installed
import subprocess
import sys

try:
    import ollama
except ImportError:
    print("Installing ollama package...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "ollama", "-q"])
    import ollama

def create_alignment_prompt(entity_uri, context, ncit_candidates, doid_candidates):
    """
    Create a prompt for Ollama to select the best aligned entity

    Args:
        entity_uri: The NCIT entity URI
        context: The context information about the entity
        ncit_candidates: List of NCIT candidate entities
        doid_candidates: List of DOID candidate entities

    Returns:
        prompt string for Ollama model
    """
    ncit_str = "\n".join([f"  {i+1}. {c}" for i, c in enumerate(ncit_candidates[:10])])
    doid_str = "\n".join([f"  {i+1}. {c}" for i, c in enumerate(doid_candidates[:10])])

    prompt = f"""You are an ontology alignment expert. Given an entity from NCIT (National Cancer Institute Thesaurus) and a list of candidate entities from DOID (Disease Ontology), select the BEST alignment candidate.

NCIT Entity: {entity_uri}
Context: {context[:5000]}

Top NCIT Candidates (for context):
{ncit_str if ncit_str else "  (none)"}

Top DOID Candidates (select from these):
{doid_str if doid_str else "  (none)"}

Based on the entity description and context, which DOID candidate is the BEST alignment?
Respond ONLY with the DOID entity URI (e.g., http://purl.obolibrary.org/obo/DOID_XXXX) or 'NO_MATCH' if none are suitable.

Answer:"""

    return prompt

def process_with_ollama(entity_uri, context, ncit_candidates, doid_candidates, model='qwen3', timeout=300):
    """
    Process entity alignment using Ollama model (default: qwen3)

    Args:
        entity_uri: The NCIT entity URI
        context: The context information
        ncit_candidates: NCIT candidates list
        doid_candidates: DOID candidates list
        model: Ollama model name
        timeout: Timeout in seconds

    Returns:
        Selected DOID entity URI or 'NO_MATCH'
    """
    try:
        prompt = create_alignment_prompt(entity_uri, context, ncit_candidates, doid_candidates)

        # Call Ollama with the prompt
        response = ollama.generate(
            model=model,
            prompt=prompt,
            stream=False,
            options={'num_predict': 5000, 'temperature': 0.2}  # Low temperature for consistency
        )

        # Extract the response
        answer = response['response'].strip()

        # Validate the answer is a URI or NO_MATCH
        if 'DOID' in answer or 'NO_MATCH' in answer:
            # Extract just the URI if there's extra text
            lines = answer.split('\n')
            for line in lines:
                if 'DOID' in line or 'NO_MATCH' in line:
                    answer = line.strip()
                    break
            return answer
        else:
            return 'NO_MATCH'

    except Exception as e:
        print(f"Error processing {entity_uri}: {str(e)}")
        return 'ERROR'

print("Ollama functions defined successfully")
print(f"Testing prompt creation with first entity...")
if len(dFrameOrigin) > 0:
    # Find the first row in dFrameOrigin that has populated 'Candidates'
    first_aligned_row_index = dFrameOrigin['Candidates'].apply(lambda x: len(x) > 0).first_valid_index()
    if first_aligned_row_index is not None:
        test_row = dFrameOrigin.loc[first_aligned_row_index]
        test_prompt = create_alignment_prompt(
            test_row['entity'],
            test_row['contextLevl0'][:2000], # Use contextLevl0 for NCIT entity context
            [], # No specific NCIT candidates needed for this test scenario, pass empty list
            test_row['Candidates'][:10] # Pass the list of DOID candidates directly
        )
        print("Sample prompt created (first 500 chars):")
        print(test_prompt[:5000])
    else:
        print("No entities in dFrameOrigin have populated 'Candidates' list to test the prompt.")

Ollama functions defined successfully
Testing prompt creation with first entity...
Sample prompt created (first 500 chars):
You are an ontology alignment expert. Given an entity from NCIT (National Cancer Institute Thesaurus) and a list of candidate entities from DOID (Disease Ontology), select the BEST alignment candidate.

NCIT Entity: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99875
Context: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60671
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A13	http://ncicb.nci.nih.gov

Top NCIT Candidates (for context):
  (none)

Top DOID Candidates (select from these):
  (none)

Based on the entity description and context, which DOID candidate is the BEST alignment?
Respond ONLY with the DOID entity URI (e.g., http://purl.obolibrary.org/obo/DOID_XXXX) or 'NO_MATCH' if none are suitable.

Answer:

In [ ]:
pip install ollama

Collecting ollama
  Downloading ollama-0.6.1-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: httpx>=0.27 in /usr/local/lib/python3.12/dist-packages (from ollama) (0.28.1)
Requirement already satisfied: pydantic>=2.9 in /usr/local/lib/python3.12/dist-packages (from ollama) (2.12.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27->ollama) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9->ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9->ollama) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9->ollama) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9->ollama) (0.4.2)
Downloading ollama-0.6.1-py3-none-any.whl (14 kB)
Installing collected packages: ollama
Successfully installed ollama-0.6.1

In [ ]:
!sudo apt-get install zstd

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  zstd
0 upgraded, 1 newly installed, 0 to remove and 41 not upgraded.
Need to get 603 kB of archives.
After this operation, 1,695 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 zstd amd64 1.4.8+dfsg-3build1 [603 kB]
Fetched 603 kB in 1s (477 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package zstd.
(Reading database ... 121689 files and directories currently installed.)
Preparing to unpack .../zstd_1.4.8+dfsg-3build1_amd64.deb ...
Unpacking zstd (1.4.8+dfsg-3build1) ...
Setting up zstd (1.4.8+dfsg-3build1) ...
Processing triggers for man-db (2.10.2-1) ...

In [ ]:
!curl -sS https://ollama.ai/install.sh | bash

>>> Installing ollama to /usr/local
>>> Downloading ollama-linux-amd64.tar.zst
######################################################################## 100.0%
>>> Creating ollama user...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
WARNING: systemd is not running
WARNING: Unable to detect NVIDIA/AMD GPU. Install lspci or lshw to automatically detect and install GPU dependencies.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.

In [ ]:
!ollama pull qwen3

In [ ]:
!ollama ps

NAME    ID    SIZE    PROCESSOR    CONTEXT    UNTIL

In [ ]:
# Initialize the 'aligned' column in dFrameOrigin to store the model's selections
# This is done here to ensure it's empty before starting the alignment process, as requested previously
dFrameOrigin['aligned'] = [None] * len(dFrameOrigin)

alignment_results = {}

print("Starting Ollama alignment process...")

# Filter dFrameOrigin to only process rows that have candidates
rows_with_candidates = dFrameOrigin[dFrameOrigin['Candidates'].apply(lambda x: len(x) > 0)]

for index, row in rows_with_candidates.iterrows():
    entity_uri = row['entity']
    context = row['contextLevl0'] + " " + row['contextLevl1']
    doid_candidates = row['Candidates']

    # Call Ollama model for alignment using the new generic function name
    selected_doid = process_with_ollama(entity_uri, context, [], doid_candidates)

    # Store the result back into the 'aligned' column in the original dFrameOrigin
    dFrameOrigin.at[index, 'aligned'] = selected_doid

    print(f"Processed {entity_uri}: Aligned with {selected_doid}")

print("Ollama alignment process completed.")

# Display the updated DataFrame with the 'aligned' column populated
print("\nFinal dFrameOrigin head after Ollama alignment:")
display(dFrameOrigin.head())

# Display a few rows that actually have populated 'aligned' entities
num_final_aligned_entities = dFrameOrigin['aligned'].apply(lambda x: x is not None and x != 'NO_MATCH' and x != 'ERROR').sum()
if num_final_aligned_entities > 0:
    print("\nDisplaying a few rows from dFrameOrigin with populated 'aligned' entities:")
    display(dFrameOrigin[dFrameOrigin['aligned'].apply(lambda x: x is not None and x != 'NO_MATCH' and x != 'ERROR')].head())
else:
    print("No entities were successfully aligned by Ollama.")

Starting Ollama alignment process...
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C94330: Aligned with http://purl.obolibrary.org/obo/DOID_11328
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C94328: Aligned with http://purl.obolibrary.org/obo/DOID_0060167
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C92727: Aligned with The NCIT entity **C92727** is described as a **subclass of "Fetal Disorder"** with the definition: *"A non-neoplastic or neoplastic disorder which occurs in the fetus."* This indicates it is a **specific type of fetal disorder**, not a general category. The goal is to match this to a **specific DOID** that represents a similar condition.
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C92564: Aligned with http://purl.obolibrary.org/obo/DOID_11328
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C9185: Aligned with http://purl.obolibrary.org/obo/DOID_3615
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C91479: Aligned with NO_MATCH
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C90530: Aligned with http://purl.obolibrary.org/obo/DOID_8457
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C90523: Aligned with http://purl.obolibrary.org/obo/DOID_8573
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C89801: Aligned with http://purl.obolibrary.org/obo/DOID_9931
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C8741: Aligned with http://purl.obolibrary.org/obo/DOID_4321
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C87110: Aligned with http://purl.obolibrary.org/obo/DOID_0090023
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C85233: Aligned with http://purl.obolibrary.org/obo/DOID_0050489
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C85207: Aligned with http://purl.obolibrary.org/obo/DOID_0080201
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C85024: Aligned with http://purl.obolibrary.org/obo/DOID_0050489
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C84604: Aligned with http://purl.obolibrary.org/obo/DOID_4138
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C84600: Aligned with http://purl.obolibrary.org/obo/DOID_0050669
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C84580: Aligned with http://purl.obolibrary.org/obo/DOID_0060471
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C8040: Aligned with http://purl.obolibrary.org/obo/DOID_3086
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C80331: Aligned with http://purl.obolibrary.org/obo/DOID_1343
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C7380: Aligned with http://purl.obolibrary.org/obo/DOID_315
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C7334: Aligned with http://purl.obolibrary.org/obo/DOID_0111061
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C7076: Aligned with http://purl.obolibrary.org/obo/DOID_0060094
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C6904: Aligned with http://purl.obolibrary.org/obo/DOID_3318
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C6389: Aligned with http://purl.obolibrary.org/obo/DOID_12960
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C63743: Aligned with http://purl.obolibrary.org/obo/DOID_0110183
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C63514: Aligned with http://purl.obolibrary.org/obo/DOID_3368
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C62627: Aligned with NO_MATCH
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C62228: Aligned with http://purl.obolibrary.org/obo/DOID_315
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C62211: Aligned with http://purl.obolibrary.org/obo/DOID_315
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C62209: Aligned with http://purl.obolibrary.org/obo/DOID_3128
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C62101: Aligned with http://purl.obolibrary.org/obo/DOID_3517
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C61561: Aligned with http://purl.obolibrary.org/obo/DOID_133
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C61477: Aligned with http://purl.obolibrary.org/obo/DOID_0110061
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C61240: Aligned with http://purl.obolibrary.org/obo/DOID_0050481
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C61145: Aligned with http://purl.obolibrary.org/obo/DOID_3368
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C61143: Aligned with http://purl.obolibrary.org/obo/DOID_3641
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C60752: Aligned with http://purl.obolibrary.org/obo/DOID_3151
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C5713: Aligned with http://purl.obolibrary.org/obo/DOID_315
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C5611: Aligned with http://purl.obolibrary.org/obo/DOID_4186
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C54690: Aligned with http://purl.obolibrary.org/obo/DOID_3707
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C54287: Aligned with http://purl.obolibrary.org/obo/DOID_4186
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C54212: Aligned with http://purl.obolibrary.org/obo/DOID_0050610
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C54105: Aligned with http://purl.obolibrary.org/obo/DOID_3772
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C54037: Aligned with http://purl.obolibrary.org/obo/DOID_3119
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C53597: Aligned with http://purl.obolibrary.org/obo/DOID_3751
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C51140: Aligned with http://purl.obolibrary.org/obo/DOID_0111091
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C4993: Aligned with http://purl.obolibrary.org/obo/DOID_4084
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C49081: Aligned with http://purl.obolibrary.org/obo/DOID_3860
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C49076: Aligned with http://purl.obolibrary.org/obo/DOID_4186
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C48900: Aligned with http://purl.obolibrary.org/obo/DOID_0090023
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C4614: Aligned with http://purl.obolibrary.org/obo/DOID_8573
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C45922: Aligned with http://purl.obolibrary.org/obo/DOID_3117
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C4587: Aligned with http://purl.obolibrary.org/obo/DOID_4323
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C45481: Aligned with http://purl.obolibrary.org/obo/DOID_3184
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C45479: Aligned with http://purl.obolibrary.org/obo/DOID_0050669
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C45236: Aligned with NO_MATCH
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C45212: Aligned with http://purl.obolibrary.org/obo/DOID_0050732
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C43291: Aligned with http://purl.obolibrary.org/obo/DOID_3447
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C43289: Aligned with http://purl.obolibrary.org/obo/DOID_0050732
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C4287: Aligned with http://purl.obolibrary.org/obo/DOID_3073
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C4190: Aligned with http://purl.obolibrary.org/obo/DOID_8514
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41835: Aligned with http://purl.obolibrary.org/obo/DOID_0050668
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C4168: Aligned with http://purl.obolibrary.org/obo/DOID_8514
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41472: Aligned with http://purl.obolibrary.org/obo/DOID_3253
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41460: Aligned with http://purl.obolibrary.org/obo/DOID_0050336
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41454: Aligned with http://purl.obolibrary.org/obo/DOID_0050336
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41048: Aligned with http://purl.obolibrary.org/obo/DOID_0050456
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C4101: Aligned with http://purl.obolibrary.org/obo/DOID_3168
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41007: Aligned with http://purl.obolibrary.org/obo/DOID_0050610
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C40995: Aligned with http://purl.obolibrary.org/obo/DOID_12132
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C40219: Aligned with http://purl.obolibrary.org/obo/DOID_599
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C40060: Aligned with http://purl.obolibrary.org/obo/DOID_3168
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C39910: Aligned with http://purl.obolibrary.org/obo/DOID_0050596
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C39716: Aligned with NO_MATCH
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C39709: Aligned with http://purl.obolibrary.org/obo/DOID_0050611
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C39682: Aligned with http://purl.obolibrary.org/obo/DOID_3707
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C39679: Aligned with http://purl.obolibrary.org/obo/DOID_3707
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C39651: Aligned with http://purl.obolibrary.org/obo/DOID_3177
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C3963: Aligned with http://purl.obolibrary.org/obo/DOID_0050481
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C39621: Aligned with http://purl.obolibrary.org/obo/DOID_3196
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C3962: Aligned with http://purl.obolibrary.org/obo/DOID_0050481
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C39094: Aligned with NO_MATCH
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C38731: Aligned with http://purl.obolibrary.org/obo/DOID_0050336
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C38450: Aligned with http://purl.obolibrary.org/obo/DOID_3172
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C38442: Aligned with http://purl.obolibrary.org/obo/DOID_3172
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C38407: Aligned with http://purl.obolibrary.org/obo/DOID_3368
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C37905: Aligned with http://purl.obolibrary.org/obo/DOID_3240
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C3745: Aligned with http://purl.obolibrary.org/obo/DOID_4321
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C3727: Aligned with http://purl.obolibrary.org/obo/DOID_4186
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C37182: Aligned with http://purl.obolibrary.org/obo/DOID_3405
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C37178: Aligned with http://purl.obolibrary.org/obo/DOID_0050860
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C37151: Aligned with http://purl.obolibrary.org/obo/DOID_0050670
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C37105: Aligned with http://purl.obolibrary.org/obo/DOID_3193
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C37058: Aligned with http://purl.obolibrary.org/obo/DOID_0050489
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C37044: Aligned with http://purl.obolibrary.org/obo/DOID_0050456
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36995: Aligned with http://purl.obolibrary.org/obo/DOID_3277
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36888: Aligned with http://purl.obolibrary.org/obo/DOID_314
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36852: Aligned with http://purl.obolibrary.org/obo/DOID_3185
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36831: Aligned with http://purl.obolibrary.org/obo/DOID_0050481
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C3676: Aligned with http://purl.obolibrary.org/obo/DOID_339
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C3669: Aligned with http://purl.obolibrary.org/obo/DOID_3118
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36685: Aligned with http://purl.obolibrary.org/obo/DOID_1540
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36667: Aligned with http://purl.obolibrary.org/obo/DOID_0050430
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36656: Aligned with http://purl.obolibrary.org/obo/DOID_3151
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36628: Aligned with http://purl.obolibrary.org/obo/DOID_14681
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36558: Aligned with http://purl.obolibrary.org/obo/DOID_0050456
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36527: Aligned with http://purl.obolibrary.org/obo/DOID_0060875
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36383: Aligned with http://purl.obolibrary.org/obo/DOID_0050788
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C3618: Aligned with http://purl.obolibrary.org/obo/DOID_1893
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35996: Aligned with http://purl.obolibrary.org/obo/DOID_3178
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35987: Aligned with http://purl.obolibrary.org/obo/DOID_0050336
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35879: Aligned with http://purl.obolibrary.org/obo/DOID_3756
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35806: Aligned with http://purl.obolibrary.org/obo/DOID_3770
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35566: Aligned with http://purl.obolibrary.org/obo/DOID_12971
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35196: Aligned with http://purl.obolibrary.org/obo/DOID_13238
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35192: Aligned with http://purl.obolibrary.org/obo/DOID_807
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C35084: Aligned with The NCIT entity **C35084** is a subclass of **C28356**, which is defined as a class of **infectious and parasitic diseases endemic in tropical and subtropical zones**, including specific examples like **malaria, yellow fever, sleeping sickness, and others**. To align this with a **DOID** (Disease Ontology ID), we must identify the most specific tropical disease from the provided options that matches the context.
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34934: Aligned with http://purl.obolibrary.org/obo/DOID_1540
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34918: Aligned with http://purl.obolibrary.org/obo/DOID_3086
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34878: Aligned with http://purl.obolibrary.org/obo/DOID_3377
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34863: Aligned with http://purl.obolibrary.org/obo/DOID_3478
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34810: Aligned with http://purl.obolibrary.org/obo/DOID_3128
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34713: Aligned with http://purl.obolibrary.org/obo/DOID_3356
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34591: Aligned with http://purl.obolibrary.org/obo/DOID_3896
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34545: Aligned with NO_MATCH
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34540: Aligned with http://purl.obolibrary.org/obo/DOID_2365
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34403: Aligned with http://purl.obolibrary.org/obo/DOID_3316
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34222: Aligned with http://purl.obolibrary.org/obo/DOID_0050568
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34210: Aligned with http://purl.obolibrary.org/obo/DOID_3173
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34055: Aligned with http://purl.obolibrary.org/obo/DOID_0050560
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C34003: Aligned with http://purl.obolibrary.org/obo/DOID_3185
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C3356: Aligned with http://purl.obolibrary.org/obo/DOID_3520
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C33246: Aligned with http://purl.obolibrary.org/obo/DOID_2871
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C32877: Aligned with http://purl.obolibrary.org/obo/DOID_3120
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C32210: Aligned with NO_MATCH
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C3125: Aligned with http://purl.obolibrary.org/obo/DOID_3443
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C3037: Aligned with http://purl.obolibrary.org/obo/DOID_0050481
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C2983: Aligned with http://purl.obolibrary.org/obo/DOID_0050426
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C2982: Aligned with http://purl.obolibrary.org/obo/DOID_11328
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C2929: Aligned with http://purl.obolibrary.org/obo/DOID_7927
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C2850: Aligned with http://purl.obolibrary.org/obo/DOID_0050860
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27591: Aligned with http://purl.obolibrary.org/obo/DOID_4321
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27496: Aligned with http://purl.obolibrary.org/obo/DOID_599
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27233: Aligned with http://purl.obolibrary.org/obo/DOID_0050481
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27169: Aligned with http://purl.obolibrary.org/obo/DOID_9931
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C27012: Aligned with The NCIT entity **C27012** is associated with the context indicating it is a subclass of **C27608**, which is labeled as **"Non-Neoplastic Corneal Disorder"**. This suggests that **C27012** is a specific type of non-neoplastic corneal disorder. Among the provided DOID candidates, **DOID_14687** is explicitly defined as **"Non-neoplastic corneal disorder"** in the Disease Ontology. While **C27012** may represent a subtype, the most direct and general match for the broader category described in the context is **DOID_14687**.
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C26806: Aligned with http://purl.obolibrary.org/obo/DOID_0050669
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C21124: Aligned with NO_MATCH
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C16650: Aligned with NO_MATCH
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C150646: Aligned with http://purl.obolibrary.org/obo/DOID_0110155
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C150251: Aligned with http://purl.obolibrary.org/obo/DOID_13862
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C148371: Aligned with http://purl.obolibrary.org/obo/DOID_10773
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C142805: Aligned with http://purl.obolibrary.org/obo/DOID_0050558
Processed http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C142085: Aligned with http://purl.obolibrary.org/obo/DOID_6880

,entity,contextLevl0,contextLevl1,Candidates,aligned
0,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,[],None
1,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,[],None
2,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,[],None
3,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,[],None
4,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,[],None

Displaying a few rows from dFrameOrigin with populated 'aligned' entities:

,entity,contextLevl0,contextLevl1,Candidates,aligned
1066,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://www.w3.org/2000/01/rdf-schema#subClassO...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,[http://purl.obolibrary.org/obo/DOID_11328],http://purl.obolibrary.org/obo/DOID_11328
1067,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://www.w3.org/2000/01/rdf-schema#subClassO...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,"[http://purl.obolibrary.org/obo/DOID_0060167, ...",http://purl.obolibrary.org/obo/DOID_0060167
1341,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://www.w3.org/2000/01/rdf-schema#subClassO...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,"[http://purl.obolibrary.org/obo/DOID_3444, htt...",The NCIT entity **C92727** is described as a *...
1390,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://www.w3.org/2000/01/rdf-schema#subClassO...,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,"[http://purl.obolibrary.org/obo/DOID_4186, htt...",http://purl.obolibrary.org/obo/DOID_11328
1528,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...,http://www.w3.org/2002/07/owl#equivalentClass\...,d3679cc83c1379ce8e9baa63878680a\thttp://www.w3...,"[http://purl.obolibrary.org/obo/DOID_3196, htt...",http://purl.obolibrary.org/obo/DOID_3615

In [ ]:
# Load the gold standard from SelSample.tsv
import os

sel_sample_path = "data/SelSample.tsv"

if os.path.exists(sel_sample_path):
    sel_sample_df = pd.read_csv(sel_sample_path, sep="\t")
    print(f"Loaded {len(sel_sample_df)} gold standard alignments from SelSample.tsv")
    print(f"Columns: {list(sel_sample_df.columns)}")
    print(f"\nFirst 5 entries:")
    print(sel_sample_df.head())
else:
    print(f"File not found: {sel_sample_path}")

Loaded 381 gold standard alignments from SelSample.tsv
Columns: ['SrcEntity', 'TgtEntity', 'Score']

First 5 entries:
                                           SrcEntity  \
0  http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
1  http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
2  http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
3  http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
4  http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...

                                  TgtEntity  Score
0  http://purl.obolibrary.org/obo/DOID_4362    1.0
1  http://purl.obolibrary.org/obo/DOID_4364    1.0
2   http://purl.obolibrary.org/obo/DOID_438    1.0
3  http://purl.obolibrary.org/obo/DOID_4353    1.0
4  http://purl.obolibrary.org/obo/DOID_4359    1.0

In [ ]:
def calculate_metrics(predicted_df, gold_standard_df):
    """
    Calculate Precision, Recall, and F1-Score

    Args:
        predicted_df: DataFrame with 'entity' and 'aligned' columns
        gold_standard_df: DataFrame with 'SrcEntity' and 'TgtEntity' columns

    Returns:
        Dictionary with metrics and detailed results
    """

    # Create mapping from gold standard
    gold_standard = {}
    for idx, row in gold_standard_df.iterrows():
        src = row['SrcEntity']
        tgt = row['TgtEntity']
        if src not in gold_standard:
            gold_standard[src] = []
        gold_standard[src].append(tgt)

    # Calculate metrics
    true_positives = 0
    false_positives = 0
    false_negatives = 0

    detailed_results = []

    # Check predictions
    for idx, row in predicted_df.iterrows():
        entity = row['entity']
        predicted = row['aligned']

        # Skip error cases
        if predicted in ['ERROR', 'error', None]:
            predicted = 'NO_MATCH'

        if entity in gold_standard:
            gold_targets = gold_standard[entity]

            # Check if prediction is in gold standard
            if predicted in gold_targets:
                true_positives += 1
                status = 'TP'
            elif predicted != 'NO_MATCH':
                false_positives += 1
                status = 'FP'
            else:
                false_negatives += 1
                status = 'FN'
        else:
            # Entity not in gold standard
            if predicted != 'NO_MATCH':
                false_positives += 1
                status = 'FP'
            else:
                status = 'TN'  # True negative

        detailed_results.append({
            'entity': entity,
            'predicted': predicted,
            'gold_standard': gold_standard.get(entity, []),
            'status': status
        })

    # Add false negatives for entities in gold standard but not predicted correctly (if any missing from df)
    # The previous loop covers keys in predicted_df. If predicted_df covers all entities, this block handles leftovers?
    # In this dataset structure, dFrameOrigin contains all source entities.

    # Calculate metrics
    precision = true_positives / (true_positives + false_positives) if (true_positives + false_positives) > 0 else 0
    recall = true_positives / (true_positives + false_negatives) if (true_positives + false_negatives) > 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

    return {
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'true_positives': true_positives,
        'false_positives': false_positives,
        'false_negatives': false_negatives,
        'total_predictions': len(predicted_df),
        'detailed_results': detailed_results
    }

# Older Codes

In [ ]:
import pandas as pd
from rdflib import Graph, Literal, URIRef

# Define the SPARQL query to retrieve entities and their two-level properties
sparql_query = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?e ?eLabel ?p ?o ?oLabel ?p2 ?o2
WHERE {
    ?e rdf:type owl:Class.
    OPTIONAL { ?e rdfs:label ?eLabel . }
    ?e ?p ?o.
    OPTIONAL {
        FILTER (isURI(?o))
        ?o rdfs:label ?oLabel .
    }
    ?o ?p2 ?o2.
}
"""

# Execute the SPARQL query
query_results = datasetGraphNcit.query(sparql_query)

# Prepare data for DataFrame
ncit_data = []
# Store contexts keyed by entity URI to aggregate all parts
entity_contexts = {}

for row in query_results:
    entity_uri = str(row.e)
    e_label = str(row.eLabel) if row.eLabel else None

    p = str(row.p) if row.p else None
    o = row.o # Keep as RDFLib term to check type
    o_label = str(row.oLabel) if row.oLabel else None # Label for the direct object if it's a URI

    p2 = str(row.p2) if row.p2 else None
    o2 = row.o2 # Keep as RDFLib term to check type

    if entity_uri not in entity_contexts:
        entity_contexts[entity_uri] = {
            'parts': set() # Use a set to avoid duplicate parts for an entity
        }
        if e_label:
            entity_contexts[entity_uri]['parts'].add(e_label)

    # Add direct properties to context
    if p and o:
        # Filter out some common RDF properties that might not be useful for context string directly
        if not any(prop in p for prop in ["type", "subClassOf", "equivalentClass", "Description", "label", "comment"]):
            prop_name = p.split('#')[-1].split('/')[-1] # Get clean name

            # Determine the value to add for the object
            o_value = ""
            if isinstance(o, Literal):
                o_value = str(o)
            elif isinstance(o, URIRef):
                o_value = o_label if o_label else o.split('#')[-1].split('/')[-1]

            if o_value:
                entity_contexts[entity_uri]['parts'].add(f"{prop_name}: {o_value}")

    # Add properties of direct objects to context
    if p2 and o2:
        if not any(prop in p2 for prop in ["type", "subClassOf", "equivalentClass", "Description", "label", "comment"]):
            prop2_name = p2.split('#')[-1].split('/')[-1] # Get clean name

            # Determine the value to add for the second-level object
            o2_value = ""
            if isinstance(o2, Literal):
                o2_value = str(o2)
            elif isinstance(o2, URIRef):
                # For o2, we don't have a specific ?o2Label, so just use the URI part
                o2_value = o2.split('#')[-1].split('/')[-1]

            if o2_value:
                entity_contexts[entity_uri]['parts'].add(f"{prop2_name}: {o2_value}")

# Convert aggregated contexts to DataFrame format
for entity_uri, data in entity_contexts.items():
    # Sort parts for consistent context string generation
    context_string = " ".join(sorted(list(data['parts'])))

    ncit_data.append({
        'entity': entity_uri,
        'context': context_string.strip(),
        'alignment candidates': [],
        'target entity': None
    })

df_ncit = pd.DataFrame(ncit_data)

# Display the first few rows of the DataFrame
print(df_ncit.head())

                                              entity  \
0  http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
1  http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
2  http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
3  http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...
4  http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus...

                                             context alignment candidates  \
0  A13: BIRC3 Gene A13: MALT1 Gene A8: C116977 A8...                   []
1  A13: ALK Gene A13: CLTC Gene A8: C116977 A8: C...                   []
2  A13: ALK Gene A13: RNF213 Gene A8: C116977 A8:...                   []
3  A13: CTNNB1 Gene A13: PLAG1 Gene A8: C116977 A...                   []
4  A13: RET Gene A8: C116977 A8: C142799 A8: C142...                   []

  target entity
0          None
1          None
2          None
3          None
4          None

In [ ]:
import pandas as pd
from rdflib import Graph, Literal, URIRef

# Define the SPARQL query to retrieve entities and their two-level properties
sparql_query = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?e ?p ?o
WHERE {
    ?e ?p ?o.
    {
      SELECT DISTINCT ?e
      WHERE {
          ?e rdf:type owl:Class.

      }limit 10
    }
}
"""

# Execute the SPARQL query
query_results = query_sparql(sparql_query, datasetGraphDoid)

# Prepare data for DataFrame
ncit_data = []
# Store contexts keyed by entity URI to aggregate all parts
entity_contexts = {}

for row in query_results:
    entity_uri = str(row.e)
    e_label = str(row.eLabel) if row.eLabel else None

    p = str(row.p) if row.p else None
    o = row.o # Keep as RDFLib term to check type
    o_label = str(row.oLabel) if row.oLabel else None # Label for the direct object if it's a URI

    p2 = str(row.p2) if row.p2 else None
    o2 = row.o2 # Keep as RDFLib term to check type

    if entity_uri not in entity_contexts:
        entity_contexts[entity_uri] = {
            'parts': set() # Use a set to avoid duplicate parts for an entity
        }
        if e_label:
            entity_contexts[entity_uri]['parts'].add(e_label)

    # Add direct properties to context
    if p and o:
        # Filter out some common RDF properties that might not be useful for context string directly
        if not any(prop in p for prop in ["type", "subClassOf", "equivalentClass", "Description", "label", "comment"]):
            prop_name = p.split('#')[-1].split('/')[-1] # Get clean name

            # Determine the value to add for the object
            o_value = ""
            if isinstance(o, Literal):
                o_value = str(o)
            elif isinstance(o, URIRef):
                o_value = o_label if o_label else o.split('#')[-1].split('/')[-1]

            if o_value:
                entity_contexts[entity_uri]['parts'].add(f"{prop_name}: {o_value}")

    # Add properties of direct objects to context
    if p2 and o2:
        if not any(prop in p2 for prop in ["type", "subClassOf", "equivalentClass", "Description", "label", "comment"]):
            prop2_name = p2.split('#')[-1].split('/')[-1] # Get clean name

            # Determine the value to add for the second-level object
            o2_value = ""
            if isinstance(o2, Literal):
                o2_value = str(o2)
            elif isinstance(o2, URIRef):
                # For o2, we don't have a specific ?o2Label, so just use the URI part
                o2_value = o2.split('#')[-1].split('/')[-1]

            if o2_value:
                entity_contexts[entity_uri]['parts'].add(f"{prop2_name}: {o2_value}")

# Convert aggregated contexts to DataFrame format
for entity_uri, data in entity_contexts.items():
    # Sort parts for consistent context string generation
    context_string = " ".join(sorted(list(data['parts'])))

    ncit_data.append({
        'entity': entity_uri,
        'context': context_string.strip(),
        'alignment candidates': [],
        'target entity': None
    })

df_ncit = pd.DataFrame(ncit_data)

# Display the first few rows of the DataFrame
print(df_ncit.head())

AttributeError: eLabel

In [ ]:
sparql_query = """
      PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      PREFIX owl: <http://www.w3.org/2002/07/owl#>
      PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?e (group_concat (CONCAT(str(?p), " ",str(?o)) ; separator="FIM") as ?contextLvl0) (group_concat (CONCAT(str(?o), " ", str(?p1), " ",str(?o1)) ; separator="FIM") as ?contextLvl1)
      WHERE {
          ?e ?p ?o.
    	    ?o ?p1 ?o1.
          {
            SELECT DISTINCT ?e
            WHERE {
                ?e rdf:type owl:Class.

            }
          }
      }group by ?e limit 2
      """

In [ ]:
%load_ext cudf.pandas
import pandas as pd



def generate_dataframe(datasetOnto:rdflib.graph.Graph) -> pd.DataFrame:
    sparql_query = """
      PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      PREFIX owl: <http://www.w3.org/2002/07/owl#>
      PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
      SELECT ?e ?p ?o ?p1 ?o1

      WHERE {
          ?e rdf:type owl:Class.
          ?e ?p ?o.
    	    ?o ?p1 ?o1.

      }
      """
    query_results = datasetOnto.query(sparql_query)

    dFrame = pd.DataFrame(columns=['entity','contextLevl0','contextLevl1'])
    print("created dataframe. Now processing each row and adding to the dataframe")
    i=1
    for row in query_results:
      print(i)
      #print(row.e, row.contextLvl0, row.contextLvl1)
      nRow = {'entity':row.e, 'contextLevl0':row.p+"\t"+row.o+"\n", 'contextLevl1':str(row.o)+ "\t"+str(row.p1)+"\t"+str(row.o1)}
      #print(nRow)
      dFrame = pd.concat([dFrame, pd.DataFrame([nRow])])
      i+=1

    return dFrame

dFrameOrigin = generate_dataframe(datasetGraphNcit).reset_index(drop=True)
dFrameTarget = generate_dataframe(datasetGraphDoid).reset_index(drop=True)

ModuleNotFoundError: No module named 'cudf'

# Task
Okay, I will update the metric calculation logic and then re-run the metrics.

**Update_Metric_Calculation_Logic**: Modifying the `calculate_metrics` function in cell `ndE9C5NtuU7Z` to correctly count True Positives, False Positives, and False Negatives, specifically handling 'NO_MATCH', 'ERROR', and `None` as non-positive predictions.

**Re-run_Metrics_Calculation**: Executing the updated `calculate_metrics` function with `dFrameOrigin` and `sel_sample_df` to display the new precision, recall, and F1-score.

## Update_Metric_Calculation_Logic

### Subtask:
Modify the `calculate_metrics` function in cell `ndE9C5NtuU7Z` to correctly count True Positives, False Positives, and False Negatives, specifically handling 'NO_MATCH', 'ERROR', and `None` as non-positive predictions.

**Reasoning**:
The subtask requires modifying the `calculate_metrics` function to correctly calculate precision, recall, and F1-score by updating the logic for True Positives, False Positives, and False Negatives, specifically handling 'NO_MATCH', 'ERROR', and `None` as non-positive predictions. I will replace the existing function in cell `ndE9C5NtuU7Z` with the updated version that incorporates the specified logic.

In [ ]:
def calculate_metrics(predicted_df, gold_standard_df):
    """
    Calculate Precision, Recall, and F1-Score

    Args:
        predicted_df: DataFrame with 'entity' and 'aligned' columns (NCIT entities and their predicted DOID alignments)
        gold_standard_df: DataFrame with 'SrcEntity' and 'TgtEntity' columns (true alignments)

    Returns:
        Dictionary with metrics and detailed results
    """

    # 1. Create mapping from gold standard for easy lookup of all true targets for an entity
    gold_mapping = defaultdict(set)
    for idx, row in gold_standard_df.iterrows():
        src = row['SrcEntity']
        tgt = row['TgtEntity']
        gold_mapping[src].add(tgt)

    # 2. Create a set of (SrcEntity, TgtEntity) tuples to represent all individual true matches
    all_gold_pairs = set()
    for idx, row in gold_standard_df.iterrows():
        all_gold_pairs.add((row['SrcEntity'], row['TgtEntity']))

    # Initialize metrics
    true_positives = 0
    false_positives = 0
    detailed_results = []

    # Iterate through each prediction from the model
    for idx, row in predicted_df.iterrows():
        entity = row['entity']
        predicted_doid = row['aligned']

        current_gold_targets = gold_mapping[entity] # Get all true targets for this NCIT entity

        # Check if the model made a positive prediction (not a 'NO_MATCH' or error)
        if predicted_doid is not None and predicted_doid != 'NO_MATCH' and predicted_doid != 'ERROR':
            predicted_pair = (entity, predicted_doid)
            if predicted_pair in all_gold_pairs:
                true_positives += 1
                status = 'TP'
            else:
                false_positives += 1
                status = 'FP'
        else: # Model predicted no match or an error
            if current_gold_targets: # If there actually was a true match for this entity
                status = 'FN (model negative)' # Model missed a true positive
            else:
                status = 'TN' # Model correctly identified no match

        detailed_results.append({
            'entity': entity,
            'predicted': predicted_doid,
            'gold_standard': list(current_gold_targets), # Convert set to list for output
            'status': status
        })

    # Calculate False Negatives:
    # An FN occurs when a gold standard pair exists but was not predicted (either missed or predicted incorrectly)
    # We need to account for true matches that the model should have found but didn't predict correctly.
    # Total number of actual gold standard pairs vs. what we counted as TP.
    false_negatives = len(all_gold_pairs) - true_positives

    # Calculate metrics
    precision = true_positives / (true_positives + false_positives) if (true_positives + false_positives) > 0 else 0
    recall = true_positives / (true_positives + false_negatives) if (true_positives + false_negatives) > 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

    return {
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'true_positives': true_positives,
        'false_positives': false_positives,
        'false_negatives': false_negatives,
        'total_predictions': len(predicted_df),
        'detailed_results': detailed_results
    }

**Reasoning**:
Now that the `calculate_metrics` function has been updated, I will re-run the metrics calculation using the modified function to get the new precision, recall, and F1-score.

In [ ]:
def calculate_metrics(predicted_df, gold_standard_df):
    """
    Calculate Precision, Recall, and F1-Score

    Args:
        predicted_df: DataFrame with 'entity' and 'aligned' columns (NCIT entities and their predicted DOID alignments)
        gold_standard_df: DataFrame with 'SrcEntity' and 'TgtEntity' columns (true alignments)

    Returns:
        Dictionary with metrics and detailed results
    """

    # 1. Create mapping from gold standard for easy lookup of all true targets for an entity
    gold_mapping = defaultdict(set)
    for idx, row in gold_standard_df.iterrows():
        src = row['SrcEntity']
        tgt = row['TgtEntity']
        gold_mapping[src].add(tgt)

    # 2. Create a set of (SrcEntity, TgtEntity) tuples to represent all individual true matches
    all_gold_pairs = set()
    for idx, row in gold_standard_df.iterrows():
        all_gold_pairs.add((row['SrcEntity'], row['TgtEntity']))

    # Initialize metrics
    true_positives = 0
    false_positives = 0
    detailed_results = []

    # Iterate through each prediction from the model
    for idx, row in predicted_df.iterrows():
        entity = row['entity']
        predicted_doid = row['aligned']

        current_gold_targets = gold_mapping[entity] # Get all true targets for this NCIT entity

        # Check if the model made a positive prediction (not a 'NO_MATCH' or error)
        if predicted_doid is not None and predicted_doid != 'NO_MATCH' and predicted_doid != 'ERROR':
            predicted_pair = (entity, predicted_doid)
            if predicted_pair in all_gold_pairs:
                true_positives += 1
                status = 'TP'
            else:
                false_positives += 1
                status = 'FP'
        else: # Model predicted no match or an error
            if current_gold_targets: # If there actually was a true match for this entity
                status = 'FN (model negative)' # Model missed a true positive
            else:
                status = 'TN' # Model correctly identified no match

        detailed_results.append({
            'entity': entity,
            'predicted': predicted_doid,
            'gold_standard': list(current_gold_targets), # Convert set to list for output
            'status': status
        })

    # Calculate False Negatives:
    # An FN occurs when a gold standard pair exists but was not predicted (either missed or predicted incorrectly)
    # We need to account for true matches that the model should have found but didn't predict correctly.
    # Total number of actual gold standard pairs vs. what we counted as TP.
    false_negatives = len(all_gold_pairs) - true_positives

    # Calculate metrics
    precision = true_positives / (true_positives + false_positives) if (true_positives + false_positives) > 0 else 0
    recall = true_positives / (true_positives + false_negatives) if (true_positives + false_negatives) > 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

    return {
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'true_positives': true_positives,
        'false_positives': false_positives,
        'false_negatives': false_negatives,
        'total_predictions': len(predicted_df),
        'detailed_results': detailed_results
    }

**Reasoning**:
The `calculate_metrics` function has been updated in the previous step. Now I need to re-run the metrics calculation with `dFrameOrigin` and `sel_sample_df` and print the results to see the new precision, recall, and F1-score.

In [ ]:
import pandas as pd
import pickle
import re
from collections import defaultdict

# Calculate metrics
print("Calculating evaluation metrics...\n")

metrics = calculate_metrics(dFrameOrigin, sel_sample_df)

print("=" * 70)
print("EVALUATION RESULTS")
print("=" * 70)
print(f"\nPrecision:  {metrics['precision']:.4f}")
print(f"Recall:     {metrics['recall']:.4f}")
print(f"F1-Score:   {metrics['f1']:.4f}")

print(f"\n{'-' * 70}")
print("Detailed Breakdown:")
print(f"{'-' * 70}")
print(f"True Positives:   {metrics['true_positives']}")
print(f"False Positives:  {metrics['false_positives']}")
print(f"False Negatives:  {metrics['false_negatives']}")
print(f"Total Predictions: {metrics['total_predictions']}")

# Calculate accuracy on non-NO_MATCH predictions
non_nomatch = [r for r in metrics['detailed_results'] if r['predicted'] is not None and r['predicted'] != 'NO_MATCH' and r['predicted'] != 'ERROR']
if non_nomatch:
    correct = sum(1 for r in non_nomatch if r['status'] == 'TP')
    accuracy = correct / len(non_nomatch) if len(non_nomatch) > 0 else 0
    print(f"\nAccuracy (non-NO_MATCH): {accuracy:.4f} ({correct}/{len(non_nomatch)})")

print("\n" + "=" * 70)
print("Sample Predictions (First 20):")
print("=" * 70)

# Show sample results
sample_results = pd.DataFrame(metrics['detailed_results'][:20])
sample_results['gold_standard'] = sample_results['gold_standard'].apply(
    lambda x: x[0] if len(x) > 0 else 'NONE'
)
print(sample_results.to_string(index=False))

Calculating evaluation metrics...

======================================================================
EVALUATION RESULTS
======================================================================

Precision:  0.0063
Recall:     0.0026
F1-Score:   0.0037

----------------------------------------------------------------------
Detailed Breakdown:
----------------------------------------------------------------------
True Positives:   1
False Positives:  157
False Negatives:  380
Total Predictions: 23784

Accuracy (non-NO_MATCH): 0.0063 (1/158)

======================================================================
Sample Predictions (First 20):
======================================================================
                                                   entity predicted gold_standard status
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99875      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99873      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99869      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99866      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99856      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99853      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99850      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99847      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99845      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99831      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99743      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99741      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99724      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99721      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99707      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99705      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99573      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99570      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99544      None          NONE     TN
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C99538      None          NONE     TN